### ISSUE TITLE
It is not possible to clear all checked item by the header

### ISSUE THREAD

**Issue by lavoiekeven** [inovua/reactdatagrid#10]
- what edition are you using - community
- version for @inovua/reactdatagrid-community version 4.0.11

**What you did:**
On a list with "checkboxColumn":
I clicked on "check all". Then all item were checked.
I clicked on "Clear Check  All". Then nothing happen.

**What happened:**
All the item were supposed to be unchecked but nothing happen.

![2020-11-22-20-44-03](https://user-images.githubusercontent.com/16387206/99923444-c8167980-2d03-11eb-83bc-3e6e02cfd9ac.gif)

**Reproduction repository:**
This can be reproduce with the exemple at "Multiple selection with checkbox column". On your docs page (https://reactdatagrid.io/docs/row-selection). 

But it works with the exemple "Multiple checkbox section. DataSource + grouping + sorting + pagination - all performed remotely"

**Problem description:**
Usually when an item is checked, the icon of the header should change to 
![2020-11-22 20_27_23-Row selection _ Docs and API Reference _ ReactDataGrid by Inovua et 1 page suppl](https://user-images.githubusercontent.com/16387206/99922980-5806f400-2d01-11eb-9c72-b516d4fbbbe6.png)
But it doesn't. 

Also when all item are checked the icon should be 
![2020-11-22 20_27_33-Row selection _ Docs and API Reference _ ReactDataGrid by Inovua et 1 page suppl](https://user-images.githubusercontent.com/16387206/99922989-635a1f80-2d01-11eb-8777-4ccfaa5ac313.png)
But it doesn't.

**Suggested solution:**
Fix it.

**Comment by inovua-admin** [comment]
Thanks for reporting. Fixed in `4.0.13`
