### ISSUE TITLE
Datagrid row handler takes focus away from a cell editor when Escape key is pressed

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#101]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - latest

The datagrid's useRow hook has the following code fragment:

https://github.com/inovua/reactdatagrid/blob/v4.1.6/community-edition/hooks/useRow/index.ts#L65-L68

I think the idea is to support built-in cell editors by cancelling the editors when the Escape key is pressed. The issue with this however is that the custom cell editors may have several popup elements or more complex requirements and they should be able to handle key interactions on their own. When this code calls focus() to give a focus to a row it interferes with the focusing logic of the custom cell editors.

Suggested solution:

Provide a way to opt out of this functionality through a global property on the grid. 

You already have a property **autoFocusOnEditComplete** to be able to opt out of automatic focusing of the row in edit complete. You could introduce another one like **autoFocusOnEditEscape** or similar.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.10`
