### ISSUE TITLE
Tree Grid + Groups?

### ISSUE THREAD

**Issue by chrisdhanaraj** [inovua/reactdatagrid#102]
What edition are you using - enterprise
Version for @inovua/reactdatagrid-enterprise - latest

--

Hey there! I'm an engineer at Netflix Studios working with the library - had a feature request... or maybe just a how to. I'm essentially trying to create the following visual

![image](https://user-images.githubusercontent.com/1266014/115615967-7408c480-a2a4-11eb-82e6-0e9ab8d3349d.png)

Nodes with children in the tree, essentially, have both true children (what would go in the `nodes` key), as well as .... kind of sub-nodes; i.e., the left most checkbox would select the entire row, but I've essentially embedded a sub-grid inside the node. It lines up with the same column groupings (same data shape), but isn't _quite_ a child. It's more akin to a subgrid than anything

Is this possible with the library?

**Comment by chrisdhanaraj** [comment]
For context - the way we did this in our older homebrew edition was essentially have a "group" component that managed open/collapse state, and then had multiple rows and simply didn't render the text in the shared cell

**Comment by inovua-admin** [comment]
Depending on the shape of the data, you could implement this with either [`groupBy`](https://reactdatagrid.io/docs/grouping-rows) or probably more likely with [treegrid](https://reactdatagrid.io/docs/tree-grid).

Basically every column has a `render` function, called for every cell in that column. The render function is called with an object that has info about the current row/cell - see https://reactdatagrid.io/docs/api-reference#props-columns-render
Besides the listed properties, it also contains info about current tree node / current group, when applicable.

So if you specify a custom render function for all the columns, you can use the current row info (about whether the row is a tree node, etc) to decide whether to render content or not in any given cell. Likewise, you can use https://reactdatagrid.io/docs/api-reference#props-columns-style (with access to the same object) to customise cell styling (borders, etc)

Maybe you can even combine this (if needed) with [the column.rowspan function](https://reactdatagrid.io/docs/api-reference#props-columns-rowspan), which would skip some unnecessary `column.render` calls for the cells that should not be visible (beware `column.rowspan` is a very advanced functionality, as row order can be modified by sorting and other grid functionality, so use with caution - if you need, you can disable grid sorting or implement your own sorting via the controlled `sortInfo` prop)

Of course for the checkbox selection logic (which I see you probably want to make it recursive so selecting a node selects all children and vice-versa), you have to implement your custom algorithm, but definitely very doable and app-specific.

Hope this helps and let us know how it's going 🎉 
Would ❤️ to see this complex use-case implemented in an elegant way, as we believe our grid is very flexible and capable to deliver very advanced configurations with a (hopefully) clear and concise API 😅

**Comment by chrisdhanaraj** [comment]
Hmmmm! Yep, we're going to be using a tree grid for this - I was roughly thinking around two paths

1. Leverage `renderRow` - in this world, I'd basically render a `Fragment` that renders out the amount of subrows needed for each actual 'row'

2. If not that, then each cellRender would need to divide each cell into multiple divs. The only downside of this one is that there's no inherent grouping for each sub row, so row highlighting would become difficult I think

**Comment by chrisdhanaraj** [comment]
Just following up on some initial explorations - leveraging the columnRender, I think I can get it _visually_ to where I want it to be. What I'm not quite sure on, though, is with cell-selection; i.e., if I divide up each column with multiple `divs`, how do I register each of those divs as a separate `cell` for RDG to register

**Comment by chrisdhanaraj** [comment]
@inovua-admin - checking to see if y'all would have pointers for cell/row selection

**Comment by inovua-admin** [comment]
We've had some more thinking on your options, here's our inputs on it:

 - you should use `column.render` to skip or customise rendering on some cells, but not to divide cells into multiple cells, as it would not play well with cell selection / keyboard navigation (which one of those do you need in this scenario?)
 - if you want to skip cell rendering for some cells, better use `column.rowspan`, as that is taken into account by cell navigation/selection
 - if you don't want to use `column.rowspan`, just use `column.render` to render empty contents for empty cells. For styling cell borders, you can use `columns.style` as a function, and return `border: none` or the appropriate value you need for the specific empty cells
 -  what kind of cell selection do you need? if you want you can implement your custom cell selection logic, as we support [controlled cell selection](https://reactdatagrid.io/docs/api-reference#props-cellSelection), so you can capture arrow keys/keyboard navigation and then send the correct value for the controlled `cellSelection` prop

**Comment by chrisdhanaraj** [comment]
👋 Hey there! 

I think the biggest pain point here for me is "grouping" within the tree-grid; i.e., I have two rows of data, and then I have five rows that are children to the aforementioned two rows of data. 

So thinking through this - I was initially tring to use `column.render` to see if I could make essentially one cell in that column `two` stacked cells and adjust the row height, but, as we mentioned, that would remove both cell selection and keyboard navigation.

So if I'm _not_ using column.render to split cells, how would I add multiple rows to the same tree-grid grouping?

**Comment by chrisdhanaraj** [comment]
Taking a pass at idea 2! Thank you for the pointer, will circle back up after I give it a whirl

**Comment by chrisdhanaraj** [comment]
:wave: Hey there! I have this mostly working - I was curious if y'all have a suggestion for the best way to get `toggleRowExpandById` into a `columns.render`? I could brute-force it by appending a method to every row in `dataSourced`, but would prefer not to

**Comment by inovua-admin** [comment]
You have `toggleNodeExpand` (use it when you have treegrid) and `toggleRowExpand` (use it when you have grouping) in the object that is being passed to `column.render`. NOTE: the object passed to `column.render` is re-used, so don't store references to it, but rather use destructuring to take a reference to those methods.

If you want access to `toggleRowExpandById`, you have to go via `onReady` and get a ref to the computedProps - see https://reactdatagrid.io/docs/api-reference#props-onReady and https://reactdatagrid.io/docs/api-reference#method-toggleRowExpandById

**Comment by chrisdhanaraj** [comment]
Gotcha - given in this scenario the row that needs to be expanded is not going to be the same row that's clicked + I'm controlling expansion state because of that, I'll move that into context and revisit this. 

If I _don't_ control the expansion state, then I'll try and do the `onReady` + ref. 

Closing this one out, thank you!
