### ISSUE TITLE
Drop row arrow indicator is not hidden when the drop is no longer valid

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#108]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.7

As you see below, the dragged row is now positioned over itself after being dragged over the second row temporarily. But the drop arrow indicator is still visible.

![image](https://user-images.githubusercontent.com/11202960/115746295-74ab6480-a351-11eb-9852-8927718afb81.png)

When drop is not valid any longer the arrow should be hidden.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.9`
