### ISSUE TITLE
checkboxColumn behavior is strange

### ISSUE THREAD

**Issue by lavoiekeven** [inovua/reactdatagrid#11]
- what edition are you using - community
- version for @inovua/reactdatagrid-community 4.0.11

What you did:
On a datagrid with checkboxColumn enabled.
Click on the row, then the item is selected.
Click on another row, the item is selected but the first item is unchecked.
Click on the current checked row, then nothing happen.

What happened:
![2020-11-22-20-58-14](https://user-images.githubusercontent.com/16387206/99923917-eed5af80-2d05-11eb-8db2-cff01fe70839.gif)

**Reproduction repository:**
This can be reproduce with the exemple at "Multiple selection with checkbox column". On your docs page (https://reactdatagrid.io/docs/row-selection).

**Problem description:**
The behavior is not what we are used to see. 
But if we click directly on the checkbox it works correctly.

Loosing all checked row but clicking on another row can be disturbing.

But we can we can override the behavior with selected and onSelectionChange.

**Suggested solution:**
- Keep check status when you click on another item.
- Remove check status when you click on the row of an item checked

**Comment by inovua-admin** [comment]
Thanks for the report. We've just released `4.0.13` with a fix for #10, so the overall experience is improved.

This behavior was intended - as it gives you ability to shift-click or cmd/ctrl-click to select, like in macos finder or windows explorer. If you don't want this, configure `checkboxOnlyRowSelect: true` - see https://reactdatagrid.io/docs/api-reference#props-checkboxOnlyRowSelect
