### ISSUE TITLE
Datagrid gives no visual indication when the grid is focused, InovuaReactDataGrid--focused class set on the top element is never removed

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#111]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.7

Currently, the datagrid provides no visual indication that is has a focus. When you tab into it or tab out of it nothing changes visually. We are implementing a11y accessibility requirements for all our applications and focused state is one of the most important visuals.

When it is focused for the first time, the **InovuaReactDataGrid--focused** class is set on the top div of the grid but it never gets removed afterwards, even when the grid loses focus. Here's the proof. In this screenshot below the grid is blurred, according to the example but the CSS class is still there:

![image](https://user-images.githubusercontent.com/11202960/115785497-c5848280-a37c-11eb-8677-3b79fdea8c86.png)

Also, there is this CSS rule:

![image](https://user-images.githubusercontent.com/11202960/115785691-05e40080-a37d-11eb-9da7-230dd8ed01a9.png)
 
but i'm not sure if it has any effect because I can see none at all visually.

I think the best approach would be to have two 'focus' visuals depending on the state:

1. if there is an active row, when the grid is focused this active row should have some extra visual that shows that the grid is also focused. Maybe some kind of an extra dotted border around it or a different color of the active row borders.
2. if there is no active row the grid viewport should have some kind of visual like a dotted border around it.

Thank you!

**Comment by yurigenin** [comment]
Interesting observation is that on my iPad I can clearly see that the background of an active or selected row when it is focused is slightly different from when it is not focused meaning that it works on mobile. But on desktop browsers I do not see such an  effect at all.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.11`
