### ISSUE TITLE
cancelEdit should be defined according to the docs but it is not available on the ref.current of the grid

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#117]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.9

Your docs indicate that this method exists:
https://reactdatagrid.io/docs/api-reference#method-cancelEdit

But it does not:

![image](https://user-images.githubusercontent.com/11202960/115968285-6184ca00-a4f4-11eb-9a4c-18dd140f8ff4.png)

It used to exist in v3. Please add it back.

Thank you!

**Comment by inovua-admin** [comment]
Fixed in `v4.1.10`
