### ISSUE TITLE
Can't scroll horizontally to end of columns.  Columns being cut off

### ISSUE THREAD

**Issue by Perrottarichard** [inovua/reactdatagrid#118]
🐛 Bug

- Using community edition '@inovua/reactdatagrid-community' version: 4.1.9

Reproduced issue in this sandbox: Note* In order to view the issue, the sandbox needs to be opened in a new window.
https://codesandbox.io/s/polished-dust-dcm7c?file=/src/App.js

What you did:
I tried to scroll to the last column, but saw that my column was cut off.
![image](https://user-images.githubusercontent.com/57297531/116345715-e46a9500-a812-11eb-851f-83c33a026c77.png)

What happened:
I couldn't scroll to the end.

Suggested solution:
I don't know.
Worth noting is the series of errors in the console. Maybe these are a separate issue, maybe related.
![image](https://user-images.githubusercontent.com/57297531/116345475-63ab9900-a812-11eb-83f2-97f4e36d76ef.png)
![image](https://user-images.githubusercontent.com/57297531/116345568-981f5500-a812-11eb-94c8-02cb4ba63d52.png)

**Comment by Perrottarichard** [comment]
I just noticed a few minutes after posting this.  The issues goes away if I remove the "defaultShowEmptyRows" prop from the grid.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.12`
