### ISSUE TITLE
Enter key edit navigation issues

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#121]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` -

Relevant code or config

```javascript
import React, { useState, useCallback } from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 350 };

const isStartEditKeyPressed = ({ event }) => event.key === 'k' && event.ctrlKey;

const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, minWidth: 50, type: 'number', editable: false, },
  { name: 'name', header: 'Name', defaultFlex: 1, minWidth: 200 },
  { name: 'country', header: 'Country', defaultFlex: 1, minWidth: 200, render: ({ value })=> flags[value]? flags[value] : value },
  { name: 'city', header: 'City', defaultFlex: 1, minWidth: 200 },
  { name: 'age', header: 'Age', minWidth: 50, type: 'number', editable: false }
];

const App = () => {
  const [dataSource, setDataSource] = useState(people);

  const onEditComplete = useCallback(({ value, columnId, rowIndex }) => {
    const data = [...dataSource];
    data[rowIndex][columnId] = value;

    setDataSource(data);
  }, [dataSource])

  return (
    <div>
      <h3>Trigger inline edit via a custom keyboard shortcut: Ctrl+K</h3>
      <h4>AGE columns is not editable. Use TAB/SHIFT+TAB while editing to navigate to next/prev editable cell.</h4>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        onEditComplete={onEditComplete}
        editable={true}
        isStartEditKeyPressed={isStartEditKeyPressed}
        columns={columns}
        dataSource={dataSource}
      />
    </div>
  );
}

export default () => <App />
```

There are a couple of issues here.

1. In the example above, scroll all the way down to the last row. Double click on the first cell in the row to edit it. The grid scroll all the way up so that you cannot even see the cell you are editing. I guess, this is not even Enter key navigation issue but may be related.

What is expected:
No scrolling should occur on a double click or Ctrl+E.

2. In the example above scroll all the way up and double click on the first cell of the row. Now just start pressing Enter and see how editors of the rows below get activated. So far so good. Now as you reach the last visible row and press Enter the grid scrolls all the way up so you do not see the cell editor (This is probably related to 1.). When you hit Enter again the grid just exits the edit mode and stops navigating completely. (Similar issue would happen as you try to do a Shift+Enter navigation.)

What is expected: 
If it is the last (first) visible row the grid should scroll down (up) one row at a time and then activate the editor until all rows are exhausted. When It is a remote data source I would expect it to load the data first, then scroll one row down, then activate the editor. 

Thank you!

**Comment by inovua-admin** [comment]
Fixed in `v4.1.14`
