### ISSUE TITLE
Tab navigation issues when horizontal scroll bar is present

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#123]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.14

Relevant code or config

```javascript
import React, { useState, useCallback } from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 350 };

const columns = [
  { name: 'id', header: 'Id', defaultWidth: 300, type: 'number' },
  { name: 'name', header: 'Name', defaultWidth: 350, },
  { name: 'country', header: 'Country', defaultWidth: 200, render: ({ value })=> flags[value] ? flags[value]: value },
  { name: 'city', header: 'City', defaultWidth: 350 },
  { name: 'age', header: 'Age', defaultWidth: 250, type: 'number' }
];

const App = () => {
  const [dataSource, setDataSource] = useState(people);

  const onEditComplete = useCallback(({ value, columnId, rowIndex }) => {
    const data = [...dataSource];
    data[rowIndex][columnId] = value;

    setDataSource(data);
  }, [dataSource])

  return (
    <div>
      <h3>Grid with inline edit</h3>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        onEditComplete={onEditComplete}
        editable={true}
        columns={columns}
        dataSource={dataSource}
      />
    </div>
  );
}

export default () => <App />
```

What you did:
Make sure that you have columns wide enough that a horizontal scroll bar is present. Make sure the column 'Age' is not visible at all.

What happened:

Couple of issues here:

1. Double click on the cell 6 of the column 'Id'. Start tabbing. When an editor for the 'Age' column is activated the column is never scrolled into view, thus, user can never see what is being edited.

2. As you continue tabbing and eventually activate the cell 8 of the column 'Id', again, you never see what is being edited as the grid for some reason does not scroll the row 8 into view. Only when you hit Tab again the row gets into view but now it is the cell Mathew of the column 'Name' that is being edited.

Thank you!

**Comment by inovua-admin** [comment]
Fixed in `v4.1.15`
