### ISSUE TITLE
expandColumn property causes the entire row to be hidden

### ISSUE THREAD

**Issue by nstoertz** [inovua/reactdatagrid#125]
Broken in: "@inovua/reactdatagrid-enterprise": "4.1.14"

Any rows that return expandColumn=true are hidden. You can see this problem in your latest doc examples:
https://reactdatagrid.io/docs/api-reference#props-expandColumn

**Comment by nstoertz** [comment]
Trying out different package versions, this works in 4.0.31 but is broken in 4.0.32. 

https://github.com/inovua/reactdatagrid/compare/v4.0.31...v4.0.32

I suspect this did something unintended:
https://github.com/inovua/reactdatagrid/commit/fcffe102e2f2367ae30bdc559b0e4756c7e9a9db

**Comment by inovua-admin** [comment]
Fixed in `v4.1.15`
