### ISSUE TITLE
No option to pop up the filter menu of a column using a keyboard

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#126]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.14

On the image below the filter menu icon has a focus but I could not find a way to make the menu pop up using a keyboard key like Space or Enter.

![image](https://user-images.githubusercontent.com/11202960/116761301-78d02580-a9d4-11eb-8ecf-d9dcca00cf60.png)

**Comment by inovua-admin** [comment]
Fixed in version `5.4.0`. We add [allowRowTabNavigation](https://reactdatagrid.io/docs/api-reference#props-allowRowTabNavigation) and [rowFocusClassName](https://reactdatagrid.io/docs/api-reference#props-rowFocusClassName) props.
