### ISSUE TITLE
Several issues with active row indicator

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#129]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.15

You can use first example on this page https://reactdatagrid.io/docs/inline-edit to see the issues described below.

After updating to the version 4.1.15 I noticed several new issues with active row indicator:

1. Double-clicking on a cell to edit and then hitting an Escape key does not reactivate the current active row.

2. Double-clicking on a cell to edit and then hitting a Tab key many times to make sure editors of rows below are activated shows the initial row as active even though the edited cell now belongs to a different row:

![image](https://user-images.githubusercontent.com/11202960/117171604-3fa70500-ad88-11eb-93f3-de553001f437.png)

Note that this only happens when you use Tab key editing. As soon as the edited cell switches to a different row the initial row shows an active row indicator (borders).

3. When you use an Enter key navigation the active row indicator flashes temporarily every time you hit the Enter key.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.16`
