### ISSUE TITLE
NumericEditor: editorProps not working

### ISSUE THREAD

**Issue by carlos-fs** [inovua/reactdatagrid#132]
- what edition are you using - **community**
- version for `@inovua/reactdatagrid-community`: **4.1.16**

Relevant code or config:
**[Taken from your documentation example](https://reactdatagrid.io/docs/inline-edit)**

```typescript
const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, minWidth: 100, type: 'number' },
  { name: 'name', header: 'Name', defaultFlex: 1, minWidth: 200, maxWidth: 300 },
// This is not working on the editor
  { name: 'age', header: 'Age', minWidth: 200, type: 'number', editor: NumericEditor, editorProps: { allowNegative: false } },
  { name: 'student', header: 'Student', width: 100, render: ({ value }) => value? 'yes':'no', editor: BoolEditor },
  { 
    name: 'country',
    header: 'Country',
    defaultFlex: 1,
    width: 100,
    render: ({ value })=> flags[value]? flags[value] : value,
    editor: SelectEditor,
    editorProps: {
      idProperty: 'id',
      dataSource: countryData,
      collapseOnSelect: true,
      clearIcon: null
    }
  },
  { name: 'city', header: 'City', defaultFlex: 1, minWidth: 200 }
];
```

What you did:
Configured a column to use the `NumericEditor` and passed the following attributes to the editor using `editorProps`:
```
{
  allowNegative: false,
  allowEmpty: false,
  allowFloat: false,
}
```

What happened:

![image](https://user-images.githubusercontent.com/77641694/117502976-2becd180-af35-11eb-9408-d635722c73a4.png)
![image](https://user-images.githubusercontent.com/77641694/117502991-2f805880-af35-11eb-823e-2db0f7d945e6.png)

The editor still allowed negative numbers to be used, and checking with the React dev tools, the props were not being passed to the underlying `InovuaNumericInput`:
![image](https://user-images.githubusercontent.com/77641694/117503110-5d659d00-af35-11eb-96f0-614e752bcd59.png)
![image](https://user-images.githubusercontent.com/77641694/117503139-648cab00-af35-11eb-83c8-9562d2b5362d.png)

Reproduction repository:
You can reproduce using your own documentation example.

Problem description:
The `editorProps` attribute in the column definition is not being passed to the underlying component.

Suggested solution:
Haven't checked the code (nor tested with other editors), but I'd guess is an issue directly on the `NumericEditor`/`NumberEditor` because the `SelectEditor` works properly using the `editorProps` attribute.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.17`
