### ISSUE TITLE
  ❓ How to enable only one selection on one type of grouping row?

### ISSUE THREAD

**Issue by fstn** [inovua/reactdatagrid#138]
On a multiselect datagrid, I would like to limit the selection to one by grouping rows.

Ex: 

selection | group | xxx
[x]            |     1     | xxx
[ ]             |     1     | xxx
[ ]             |     1     | xxx
[ ]             |     1     | xxx
[x]            |     2    | xxx
[x]            |     3    | xxx

**Comment by fstn** [comment]
Ant idea?

**Comment by inovua-admin** [comment]
Can you give me more details or a codesandbox example, please? If you have multiple selection and grouping rows, you can select only one row if you'd like.
