### ISSUE TITLE
How to drag and copy selected cells?

### ISSUE THREAD

**Issue by seta-sarah** [inovua/reactdatagrid#139]
How can do as video: https://drive.google.com/file/d/1I_h-nFOuOBiWe0qV-Gw7ayiToX5VAX08/view?usp=sharing

**Comment by inovua-admin** [comment]
[multiSelect](https://reactdatagrid.io/docs/api-reference#props-multiSelect) property activates multiple cell selection, but with this functionality the value of a cell cannot be copied on all selected cells
