### ISSUE TITLE
Uncaught (in promise) TypeError: window.moment is not a function in filterTypes.js

### ISSUE THREAD

**Issue by Ace-ezer** [inovua/reactdatagrid#14]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community` is 4.0.16 -

Error encountered in filterTypes.js (specifically in DateFilters)

```
Uncaught (in promise) TypeError: window.moment is not a function
    Choo 11
    React 7
    unstable_runWithPriority Choo
    React 4
    unstable_runWithPriority Choo
    React 19
    unstable_runWithPriority Choo
    React 4
    Choo 5
    React 5
[learn more]
```
Package.json
```
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@inovua/reactdatagrid-community": "^4.0.16",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "axios": "^0.21.1",
    "bootstrap": "^4.5.3",
    "moment": "^2.29.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-moment": "^1.1.1",
    "react-redux": "^7.2.2",
    "react-router-dom": "^5.2.0",
    "react-scripts": "4.0.1",
    "reactstrap": "^8.8.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "proxy": "http://localhost:5000"
}
```
I added DateFilter exactly how it is given in the documentation except I used local dataSource instead of remote dataSource. Also, I am using the Community version for my personal project. Component code is given below:
```
import React from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-community'
import '@inovua/reactdatagrid-community/index.css'

import NumberFilter from '@inovua/reactdatagrid-community/NumberFilter'
import DateFilter from '@inovua/reactdatagrid-community/DateFilter'

const moment = require('moment')
const gridStyle = { minHeight: 600 }

const people = [
    {id: 1, name: "Arpit", age: "22", city: "Lucknow", birthDate: new Date("1990-02-07")},
    {id: 2, name: "Gangwar", age: "21", city: "Bareilly", birthDate: new Date("1996-12-23")},
    {id: 3, name: "Apu", age: "21", city: "Bangalore", birthDate: new Date("1998-01-11")}
]

const filterValue = [
    { name: 'name', operator: 'startsWith', type: 'string', value: '' },
    { name: 'age', operator: 'gte', type: 'number', value: 21 },
    { name: 'city', operator: 'startsWith', type: 'string', value: '' },
    {
      name: 'birthDate',
      operator: 'before',
      type: 'date',
      value: ''
    }
]

const columns = [
    { name: 'id', header: 'Id', defaultVisible: false, defaultWidth: 80, type: 'number' },
    { name: 'name', header: 'Name', defaultFlex: 1 },
    { name: 'age', header: 'Age', defaultFlex: 1, type: 'number', filterEditor: NumberFilter },
    {
      name: 'birthDate',
      header: 'Bith date',
      defualtFlex: 1,
      minWidth: 200,
      filterEditor: DateFilter,
      filterEditorProps: (props, { index }) => {
        // for range and notinrange operators, the index is 1 for the after field
        return {
          dateFormat: 'MM-DD-YYYY',
          cancelButton: false,
          highlightWeekends: false,
          placeholder: index === 1 ? 'Created date is before...': 'Created date is after...'
        }
      },
      render: ({ value, cellProps }) => {
        return moment(value).format('MM-DD-YYYY')
      }
    },
    { name: 'city', header: 'City', defaultFlex: 1 },
]

const ListComponent = () => {
    
    return(
        <div>
            <h3>Grid with default filter value</h3>
        <ReactDataGrid
            idProperty="id"
            style={gridStyle}
            defaultFilterValue={filterValue}
            columns={columns}
            dataSource={people}
        />
        </div>
    )
}

export default ListComponent
```

### What happened:
While using the date filter, If I select a date say "07/12/2020" the following error appears:
![Screenshot from 2021-01-01 16-48-38](https://user-images.githubusercontent.com/34399051/103438001-092f7100-4c54-11eb-94aa-c2fbe8fe0dfe.png)

This error only occurs while using date filter. Rests are just warnings about using StrictMode in react. 

### Reproduction repository:
Given below is a codesandbox link with the above mentioned components and the dependencies. Please open this link separately.

[https://codesandbox.io/s/modest-pare-v5sum?file=/src/ListComponent.js](url) 

Just try and use Date filter and you can see the error.

### Problem description:
It says Window.moment is not a function. I am using Ubuntu 20.04. This error completely renders the date filter useless and result in the crash of the application. Date filter also does not filters the dates.

### Suggested solution:
I think using moment from moment.js instead of window.moment might work but I am not sure. I am hoping to find a solution so please look into it.

**Comment by marquetd** [comment]
I reproduce it

**Comment by inovua-admin** [comment]
The  docs clearly say https://reactdatagrid.io/docs/filtering#date-filters
![Screenshot 2021-01-07 at 15 30 58](https://user-images.githubusercontent.com/72134617/103898262-5a7cac00-50fd-11eb-8224-153240046ccb.png)
This is because we don't want to require/include the moment.js library in our code, as it's quite heavy, as not everyone will use date filters. As a consequence, we take it from the global namespace - `window.moment` so you can easily enable this by doing
```js
import moment from 'moment';

window.moment = moment```

**Comment by Ace-ezer** [comment]
Thank you! It worked and there are no more errors. A suggestion is that, add that exact line of code in the actual documentation. As I was using momentjs and did read those docs but still wasn't able to figure it out on how and where to add that line, as in all the example there is no mention of momentjs in the actual code.

Again, Thank you. I'll be closing this issue now.

**Comment by inovua-admin** [comment]
@Ace-ezer Thanks for the suggestion - we've updated our docs regarding date filters
https://reactdatagrid.io/docs/filtering#date-filters

**Comment by SAnsAN-9119** [comment]
@inovua-admin But there is still no information about "window.moment = moment" in the documentation! I'm glad I found this thread!
"window.moment = moment" - solved everything!

**Comment by SWA-petdam** [comment]
Hi @inovua-admin,
As momentjs is now [legacy](https://momentjs.com/docs/#/-project-status/), do you plan to support any other lib for the purpose of this filter e.g. ?
