### ISSUE TITLE
Ability to disable clearing of multiple selected rows when a row becomes active

### ISSUE THREAD

**Issue by andrewhawk1ns** [inovua/reactdatagrid#141]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.1.17

Relevant code or config

```

    const handleSelectionChange = React.useCallback(
        ({ selected: selection, data }) => {
            setSelected(prevSelected =>
                empty(selection) ? {} : { ...prevSelected, ...selection }
            );
            if (onSelect) onSelect(data);
        },
        [onSelect]
    );

 <ReactDataGrid
                idProperty="id"
                selected={selected}
                checkboxColumn
                enableSelection
                onSelectionChange={handleSelectionChange}
            />
```

What you did:

What happened:

I selected multiple rows with shift click. Then selected a single row afterwards.

Problem description:

When I single click a row during multiple row selection, it clears the multiple row selection. I'm looking to get either data saying when a row is specifically de-selected (someone toggles a checkbox off or the header clear checkbox at the top is toggled) or some way to disable this. I only want to de-select a row when someone specifically unchecks a checkbox or hits the clear header checkbox not when a row is clicked after or during multiple row selection.

Suggested solution:

Provide some data to say a row is specifically de-selected instead of just the selection result.

**Comment by inovua-admin** [comment]
There is a way to unselect specific rows after you select multiple rows with `shift + click`, you can unselect them with `cmd + click` on that specific row.

**Comment by tiriana** [comment]
> * what edition are you using - community
> * version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.1.17
> 
> Relevant code or config
> 
> ```
> 
>     const handleSelectionChange = React.useCallback(
>         ({ selected: selection, data }) => {
>             setSelected(prevSelected =>
>                 empty(selection) ? {} : { ...prevSelected, ...selection }
>             );
>             if (onSelect) onSelect(data);
>         },
>         [onSelect]
>     );
> 
>  <ReactDataGrid
>                 idProperty="id"
>                 selected={selected}
>                 checkboxColumn
>                 enableSelection
>                 onSelectionChange={handleSelectionChange}
>             />
> ```
> 
> What you did:
> 
> What happened:
> 
> I selected multiple rows with shift click. Then selected a single row afterwards.
> 
> Problem description:
> 
> When I single click a row during multiple row selection, it clears the multiple row selection. I'm looking to get either data saying when a row is specifically de-selected (someone toggles a checkbox off or the header clear checkbox at the top is toggled) or some way to disable this. I only want to de-select a row when someone specifically unchecks a checkbox or hits the clear header checkbox not when a row is clicked after or during multiple row selection.
> 
> Suggested solution:
> 
> Provide some data to say a row is specifically de-selected instead of just the selection result.

I have the exact same need, and ctrl + click does not really solve my problem, because my users are used to selecting multiple rows with checkboxes and them clicking on some cells (for example to copy them or out of habit, the reason is irrelevant) and they often lose their selection. Is is there a way to prevent de-selection of multiple rows when a single row is selected in the code, and not forcing a change of behaviour on the user?

**Comment by tiriana** [comment]
For the time being I switched from `defaultSelected` to `selected` and I control the selection elsewhere.
