### ISSUE TITLE
Using a percentile minHeight in style property

### ISSUE THREAD

**Issue by tamir-jether** [inovua/reactdatagrid#144]
(asking here, since its impossible to ask in stackoverflow, because the tag doesnt exists)

Is it possible to use a percentile minHeight property when i define a style for the ReactDataGrid?

Right now i have something like that:

```
 const gridStyle = {
        minHeight: 480,
        border: '1px solid #7986cb',
        boxShadow: '0 0 8px 2px rgba(121, 134,203, 0.5)'
 }
```

```
<ReactDataGrid
        idProperty="id"
        columns={columns}
        dataSource={data}
        style={gridStyle}
 />
```

Is there a way to change minHeight to be percentile?

**Comment by inovua-admin** [comment]
Yes, you can use percentage as a string for minHeight, like in example bellow.

```
 const gridStyle = {
        minHeight: '50%',
        border: '1px solid #7986cb',
        boxShadow: '0 0 8px 2px rgba(121, 134,203, 0.5)'
 }
```
