### ISSUE TITLE
onColumnOrderChange and reorderColumns are missing from types

### ISSUE THREAD

**Issue by mijikim** [inovua/reactdatagrid#147]
Hello,

It seems like `onColumnOrderChange` and `reorderColumns` are missing from types.  I've looked in `TypeComputedProps`, `TypeDataGridProps`, and defaultProps.  It would be great if those two props get typed. 

Thank you!

version: `@inovua/reactdatagrid-enterprise@4.1.17`

**Comment by inovua-admin** [comment]
Fixed in `v4.1.21`
