### ISSUE TITLE
💡 Ability to show a custom proxy on column reordering

### ISSUE THREAD

**Issue by mijikim** [inovua/reactdatagrid#148]
Currently, the library has a handy `renderRowReorderProxy` function that allows customization of proxy when row gets reordered. It will be great if the team can expose a similar function (ie. `renderColumnReorderProxy`) for when a column gets reordered.  

version: `@inovua/reactdatagrid-enterprise": 4.1.17`

**Comment by inovua-admin** [comment]
Fixed in `v4.1.23`
