### ISSUE TITLE
🐛Cannot inline edit a cell in the last row after expanding and collapsing the sub rows

### ISSUE THREAD

**Issue by ecullu** [inovua/reactdatagrid#149]
- what edition are you using - enterprise
- version for @inovua/reactdatagrid-enterprise - 4.1.17

What you did:
1. Scroll to the bottom of the grid
2. Expand the last row
3. Collapse the last row
4. Try to inline edit a cell in the last row

What happened:
Blank screen - Uncaught Type Error
![image](https://user-images.githubusercontent.com/17970524/120521289-64e45e80-c39a-11eb-88e8-1c4b4ebf1894.png)

Error caught in file: @inovua\reactdatagrid-community\Layout\ColumnLayout\Content\List.js 
![image](https://user-images.githubusercontent.com/17970524/120523307-5e0a1b80-c39b-11eb-8f6f-dca24956b093.png)

Looks like InovuaVirtualListRows row is null for the last row in the grid.
![image](https://user-images.githubusercontent.com/17970524/120521072-25b60d80-c39a-11eb-8dd2-0869775570f5.png)

Note: I can only reproduce it when I scroll to the bottom of the grid and try to inline a edit a cell.

**Comment by inovua-admin** [comment]
Please provide a reproduction example or repo with create-react-app, either as a standalone repo or a codesandbox example.

**Comment by ecullu** [comment]
> Please provide a reproduction example or repo with create-react-app, either as a standalone repo or a codesandbox example.

[https://codesandbox.io/s/modest-moore-qn7gj
](https://codesandbox.io/s/modest-moore-qn7gj
)
Steps to reproduce: 

1. Scroll to the bottom of the grid
2. Expand the last row
3. Collapse the last row
4. Try to inline edit the 'Name' in the last row

You will notice that you can inline edit a Name cell (parent row) of other cells.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.23`
