### ISSUE TITLE
 💡 Get Column width based on text header length

### ISSUE THREAD

**Issue by fstn** [inovua/reactdatagrid#151]
Provide a auto column width mode that is by default the length of the column header.

**Comment by yurigenin** [comment]
What is an auto column width mode? If it is supposed to calculate the content width for every cell of that column then it is not practical as the grid virtualizes the row display so it cannot rely on what is currently 'visible'.

**Comment by fstn** [comment]
I would do it only on column header, 
This is my datagrid:
![image](https://user-images.githubusercontent.com/2936857/121087534-360b2580-c7aa-11eb-8968-c97188fb367f.png)

My client wants to change the header label and he would like that the grid column fit the label size.

**Comment by yurigenin** [comment]
You will probably be better off implementing it yourself in your application. You can use the canvas element to measure the text of the title and set the new column width:

```
 const canvasContext = document.createElement('canvas').getContext('2d');

 canvasContext.font = <your font style> // i.e. 'bold 12px "Open Sans", Helvetica, Arial, sans-serif';
 const columnWidth = Math.ceil(canvasContext!.measureText(<the column header label text>).width) + <some extra padding/margin>
```

You might want to cache the canvas context so that you can reuse it later.

Hope it helps.

**Comment by fstn** [comment]
Thank you so much
