### ISSUE TITLE
Feature request: Support rendering our own expand/collapse controls when using TreeGrid

### ISSUE THREAD

**Issue by nstoertz** [inovua/reactdatagrid#159]
Version: @inovua/reactdatagrid-enterprise@4.1.20

When rendering rows in using TreeGrid APIs, https://reactdatagrid.io/docs/tree-grid, we wish to render our own buttons to control expansion and collapsing rows, and to show loading states

We can render everything we need using cellProps.{nodeCollapsed, nodeLoading, toggleNodeExpand}, but we don't currently have a way to hide the existing expand / collapse controls within the grid.

Overriding styles

    '& .InovuaReactDataGrid__cell > svg': {
      display: 'none'
    }

doesn't really work for us, as we don't want to hide other svgs in the cell.

An additional property on the grid could help.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.22`

**Comment by nstoertz** [comment]
It looks like the fix added two properties `renderTreeCollapseTool` and `renderTreeExpandTool` that we can use to render our own UI when collapsed and expanded. A few problems here:

1) The API doesn't provide an easy way to skip rendering the collapse/expand tool altogether. 
2) The API doesn't provide a way to customize the styling of the nodeLoading icon

I'd slightly prefer to have a single callback prop, eg `renderExpandTool` where I could pass either a boolean value (eg. pass false to skip rendering) or a callback function that took all props needed for rendering regardless of collapsed state (eg. `isExpanded`, `isLoading`, `rtl` and `onToggle`.

If you prefer not to break the current API, it could be fine to just add a `renderTreeLoadingSpinner` prop, and to support passing false (or returning null) for all 3 props.

Also, would be nice to document these properties.
