### ISSUE TITLE
"clearAll"  button in filter editor not working properly in remote filter mode

### ISSUE THREAD

**Issue by msanli220** [inovua/reactdatagrid#160]
Hello,
I'm having a problem with filtering in react data grid. When i change the remoteFilter = {true} for server-side filtering. The filter editor does not let me to handle clear and clearAll buttons. Also, it doesn't work properly in remote filter mode. For example:
when i search string and click clearAll it only removes the last letter/number. It's not removing all of the string.

![First](https://user-images.githubusercontent.com/16512549/125411976-24c7c100-e3c7-11eb-8a77-52268acca1fd.PNG)
![Second](https://user-images.githubusercontent.com/16512549/125412093-f1594d32-cd11-4c8e-b501-9c327d3e51f2.PNG)

In addition, i tried to remove this button but there is no way to control it.  How can i fix or remove it?

**Comment by inovua-admin** [comment]
We cannot reproduce your issue, please provide a reproduction example or repo with create-react-app, either as a standalone repo or a codesandbox example.

**Comment by msanli220** [comment]
Here is an Example of remote filter madewith react data grid. If you search a string more than 1 letter  and click clear all button you can see the problem that i facing with. It removes only  1 letter.
[https://github.com/msanli220/reactDataGrid-remoteFilterMode](url)

**Comment by msanli220** [comment]
> We cannot reproduce your issue, please provide a reproduction example or repo with create-react-app, either as a standalone repo or a codesandbox example.

 Here is an Example of remote filter madewith react data grid. If you search a string more than 1 letter and click clear all button you can see the problem that i facing with. It removes only 1 letter.
https://github.com/msanli220/reactDataGrid-remoteFilterMode

**Comment by inovua-admin** [comment]
We looked at your application and the filters object must contain a value, you can specify an empty string by default.

**Comment by msanli220** [comment]
but it only works when first time of filtering some string. The same problem occurs on the second try. I'm telling you for your information.
