### ISSUE TITLE
Auto height grid table

### ISSUE THREAD

**Issue by danielpaz6** [inovua/reactdatagrid#162]
Is it possible to get auto full height for the grid table?

**Comment by inovua-admin** [comment]
When the minHeight is given to 100%, the grid will take the full height of the container in witch it is placed. For example:
```jsx
<body style={{ height: '100vh' }}>
  <ReactDataGrid 
    ...
    style={{ minHeight: '100%' }}
  />
</body>
```

**Comment by danielpaz6** [comment]
@inovua-admin 
That's not what I meant, because I don't have a body to define '100vh'. the table is inside div, and I want to use the native scrollbar of the whole page (=body) and not Reactdatagrid one.

Material-UI for example has attribute for auto height

**Comment by marcselman** [comment]
Yeah, is this possible? So when using pagination and showing 50 rows for example, can we just show all 50 rows without a container with scrollbar?
