### ISSUE TITLE
Support skipping rendering the collapse/expand tool

### ISSUE THREAD

**Issue by nstoertz** [inovua/reactdatagrid#164]
`renderTreeCollapseTool` and `renderTreeExpandTool` can be used to render our own collapse and expand icons, but can't be used to skip rendering the icons and the loading spinner altogether. 

Our use case is to render the tool on the right hand-side of the row, make the entire row clickable, and to provide a different UI treatment when the node is loading.

Other issues with the current API, as it currently stands:
1) Doesn't allow styling the nodeLoading icon
2) Makes it difficult to provide RTL support
3) Isn't documented on the docs site

I'd prefer to have a single callback prop, eg `renderExpandTool` where I could pass either a boolean value (eg. pass false to skip rendering) or a callback function that took all props needed for rendering regardless of collapsed state (eg. `isExpanded`, `isLoading`, `rtl` and `onToggle`.

If you prefer to keep the current API, it could be OK to add a `renderTreeLoadingSpinner` prop, and to support passing false (or returning null) for all 3 props.

_Originally posted by @nstoertz in https://github.com/inovua/reactdatagrid/issues/159#issuecomment-883521264_

**Comment by inovua-admin** [comment]
Fixed in `v4.1.26`
