### ISSUE TITLE
💡 Feature Requests: to enable lifecycles/hooks in the custom cell renderer?

### ISSUE THREAD

**Issue by CCinCapital** [inovua/reactdatagrid#169]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - ^4.1.24

What you did:

> Tried to use lifecycles/hooks in custom cell renderer

What happened:

 - For FunctionComponent: `Uncaught Error: Invalid hook call. `
 - For ClassComponent: `Uncaught TypeError: Cannot call a class as a function`

Relevant code or config:

```javascript
// Column Config
const COLUMNS: IColumn[] = [{
  name: 'code',
  header: 'Code',
  render: CodeRenderer,
}];
```

```javascript
// CustomCellRenderer
const CodeRenderer: React.FC = (props) => {
  const { value } = props;

  const [validating, setValidating] = React.useState(false);

  React.useEffect(() => {
      setValidating(true);
  }, [value]);

  return (
    <div style={{ display: 'inline-block' }}>
      {value} {validating ? '+' : ''}
    </div>
  );
};
```

```javascript
// CustomCellRenderer
class CodeRenderer extends React.PureComponent {
  constructor(props) {
    super(props);

    this.state = {
      validating: false,
    };
  }

  render() {
    const { value } = this.props;
    const { validating } = this.state;

    return (
      <div style={{ display: 'inline-block' }}>
        {value} {validating ? '+' : ''}
      </div>
    );
  }
}
```

Problem description:

https://github.com/inovua/reactdatagrid/blob/5aef08d2ba4710bf3801076660c0b6def104d0bc/community-edition/Layout/ColumnLayout/Cell/index.tsx#L715-L721

**Comment by simontoulouze** [comment]
Hello, 
Any news on that feature request ? Anyone has managed to find another way of doing ?
We'd really need to be able to use hooks in the custom cell renderer. 
Best regards

**Comment by inovua-admin** [comment]
Hello,
It's fixed in the previous versions, you can pass an entire component to column render function, using react hooks, like in the [example](https://github.com/inovua/reactdatagrid/blob/master/examples/pages/prop-render/index.page.tsx).
