### ISSUE TITLE
grouping style is broken in RTL

### ISSUE THREAD

**Issue by goldylucks** [inovua/reactdatagrid#17]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

What you did: implemented a grid with grouping in rtl mode

What happened: ui is broken
![image](https://user-images.githubusercontent.com/6963212/104210168-3ab9f080-543b-11eb-83c2-3d0924ddaca4.png)

Reproduction repository:
https://codesandbox.io/s/gracious-sun-khueb

Problem description:
UI is broken

Suggested solution:
Fix it :)

**Comment by inovua-admin** [comment]
should be fixed in `v4.0.21`

**Comment by inovua-admin** [comment]
@goldylucks can you still reproduce the issue on your side with the new version?
