### ISSUE TITLE
🐛 Certain column style properties just aren't being recognized

### ISSUE THREAD

**Issue by tprebenda** [inovua/reactdatagrid#173]
- what edition are you using - enterprise 
- version for 4.1.24

Relevant code or config

while defining a column:
 ```
header: 'Sources',
defaultLocked: 'end',
defaultWidth: 85,
minWidth: 75,
headerEllipsis: false,          // problem here: not recognized
textAlign: 'center', 
...COLUMN_DEFAULT_PROPS,
 ```

for the actual ReactDataGrid:
 ```
 columns={columns}
  dataSource={dataSource}
  style={gridStyle}
  headerProps={headerProps}        // also not recognized

 ```

What you did:

What happened:
Can't manipulate certain style values: headerEllipsis is not recognized, headerProps is not recognized. There also is seemingly no way to change the default padding within headers/cells... I've put a padding value (i.e. '3px) in the gridStyles, headerStyles, etc and nothing changes it. 
EDIT: You can see in the web inspector that there is a built-in padding value of 8px for the cells. Setting the padding to 3px (as mentioned above) only adds that value to the initial 8px, making it bigger. There must be some way to change this default value!
I also tried defining columns.style to incorporate these changes, but this didn't do anything at all. This is what I added:
`const cellStyle = { padding: '3px', textOverflow: 'clip', headerEllipsis: false, textEllipsis: false }`
And in the column properties:
`..., style: cellStyle }`

Looking at the web inspector, I can see these styles reflected in the parent div of the cell, but the underlying div that holds the default styles (i.e. 8px padding) and the content itself is unaffected. I still see ellipsis, and I still see 8px padding (plus the 3 I added on top by trying to overwrite it).

Here are the errors from trying to use the unrecognized properties:
![image](https://user-images.githubusercontent.com/51833623/129241303-dd32ebc0-6f75-4a49-aa7a-851de6741b1b.png)

Reproduction repository:

(Can't share code, no point in making a sandbox for it because it clearly works in your API reference docs, just not in my project)

Problem description:
Trying to shrink our grid down to fit as much data as possible in as little space as possible, but we are losing tons of space to unnecessary padding, ellipsis, etc. Need to be able to adjust these properties

Suggested improvements:
Make sure we can actually manipulate some of the properties of the grid, obviously haha.
Also make it easier to manipulate pre-defined style settings, like padding
Also make it so that if you have a cell/header that is too small to fit the full text (with or without ellipsis), add a tooltip or something that displays the full text on hover.

**Comment by muazcoban** [comment]
i need a similar development

**Comment by inovua-admin** [comment]
Fixed in previous versions. See [columns.headerEllipsis](https://reactdatagrid.io/docs/api-reference#props-columns-headerEllipsis), [headerProps](https://reactdatagrid.io/docs/api-reference#props-headerProps), [columns.headerProps.style](https://reactdatagrid.io/docs/api-reference#props-columns-headerProps-style) props.
