### ISSUE TITLE
Scrolling drop-down issue with SelectEditor

### ISSUE THREAD

**Issue by nesbittw-saic** [inovua/reactdatagrid#174]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.1.24

Relevant code or config

```
Please view the CodeSandbox example: https://codesandbox.io/s/crimson-flower-nu87s
```

What you did:  I created a SelectEditor drop-down with several values in it, and configured it as the cell editor for the "Country" column.

What happened:  When I click on the cell to open the SelectEditor, the drop-down to select the value has a scroll bar due to the number of values.  However, when trying to scroll either by clicking and dragging the scroll bar or using the mouse wheel, the drop-down flickers and disappears while scrolling, then appears again after the user has stopped scrolling.

Please see the CodeSandbox for a demo of the issue.  Click on a cell value in the Country column to open the SelectEditor and see the issue.

Reproduction repository: Please view the CodeSandbox example: https://codesandbox.io/s/crimson-flower-nu87s

Problem description:  The problem is that the SelectEditor drop-down that appears when clicking on the cell flickers and disappears when trying to scroll down through the values.  This makes it hard to select a value from a list that is large enough to require a scroll bar.  This issue does not appear when only a few values are passed to the SelectEditor, as there is no scrolling needed.  Also note this does not affect scrolling of the grid itself, only the drop-down from the SelectEditor.

Suggested solution:  I attempted to manually set the Z-index of the drop-down class to a large number thinking this was the issue, but the flickering remains.  I also found that increasing the height of the grid with minHeight: CSS to a large enough value prevents the scroll bar from appearing, but this is not a full work around for our usage since we will eventually have too many values to fit in the SelectEditor drop-down without requiring scrolling.

**Comment by inovua-admin** [comment]
Fixed in `v4.2.4`
