### ISSUE TITLE
🐛 Cell selection does not work

### ISSUE THREAD

**Issue by brianqvpham** [inovua/reactdatagrid#176]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.1.24

Relevant code or config - demo from [https://reactdatagrid.io/docs/api-reference#props-cellSelection](https://reactdatagrid.io/docs/api-reference#props-cellSelection)

```javascript
import React, { useState } from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 };

const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, defaultWidth: 60, type: 'number' },
  { name: 'name', header: 'Name', defaultFlex: 1 },
  { name: 'country', header: 'Country', defaultFlex: 1,
    render: ({ value })=> flags[value]? flags[value] : value
  },
  { name: 'city', header: 'City', defaultFlex: 1 },
  { name: 'age', header: 'Age', defaultFlex: 1, type: 'number' }
];

const App = () => {
  const [cellSelection, setCellSelection] = useState({"2,name": true, "2,city": true});

  return (
    <div>
      <h3>Multiple cell selection</h3>
      <p>Selected cells: {cellSelection.length == 0 ? 'none' : JSON.stringify(cellSelection, null, 2)}.
      </p>
      <ReactDataGrid
        idProperty="id"
        cellSelection={cellSelection}
        onCellSelectionChange={setCellSelection}
        style={gridStyle}
        columns={columns}
        dataSource={people}
      />
    </div>
  );
}

export default () => <App />
```

What you did: Replicate the demo

What happened:
![image](https://user-images.githubusercontent.com/9257770/130000707-72a1e530-a7df-4344-b9fb-21af6b211c5d.png)

Reproduction repository: [https://codesandbox.io/s/keen-lamarr-u14ob?file=/src/App.tsx](https://codesandbox.io/s/keen-lamarr-u14ob?file=/src/App.tsx)

Problem description:

The code fails to compile when trying to specify onCellSelectionChange. From the [docs](https://reactdatagrid.io/docs/cell-selection#cell-selection) it appears that this is necessary to specify in order to get cell selection working. Thus, I'm not enable to cell selection. Does this feature still exist? If not, the documentation should be updated accordingly.

**Comment by inovua-admin** [comment]
You have to import the styles too. 
`import '@inovua/reactdatagrid-community/index.css';`
