### ISSUE TITLE
Column Virtualization does not work

### ISSUE THREAD

**Issue by chrisdhanaraj** [inovua/reactdatagrid#178]
Reproduction: https://codesandbox.io/s/async-snowflake-sj8j2?file=/src/columnConfig.js

At > 14 columns (the configured default), columns get very jumbled up after a horizontal scroll. I can disable column virtualization, but I need that for performance on the larger data sets

**Comment by chrisdhanaraj** [comment]
Ah update - stripped the repro of almost everything; apparently defining a `headerHeight` breaks column virtualization

**Comment by inovua-admin** [comment]
Fixed in `v4.2.2`
