### ISSUE TITLE
collapsing all groups and then opening a top level group will open all children groups.

### ISSUE THREAD

**Issue by goldylucks** [inovua/reactdatagrid#18]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

What you did:
called `collapseAllGroups` and then opened a top level group

What happened:
All children groups were opened as well.
![image](https://user-images.githubusercontent.com/6963212/104210583-bcaa1980-543b-11eb-88c8-3cc5f5385854.png)

Reproduction repository:
https://codesandbox.io/s/throbbing-fire-jjc6g?file=/src/App.js

Problem description:
This only happens when calling `collapseAllGroups` and then drilling down. Closing groups manually and then reopening them does not produce this behavior.

Makes the grid harder to navigate. when I drill down a group, I'm only interested in the next level of drill, not all the way down for all the subgroups. We use it for initial display. We have customers with 8 levels of drill down, and they start the view with only seeing the top level group, click one to expand, and bam, all the way down to level 8.

Suggested solution:
whatever happens behind the scenes when manually closing all groups, make the same happen when calling `collapseAllGroups`.

**Comment by inovua-admin** [comment]
Thanks for the feedback. We're working on improving this functionality as suggested

**Comment by goldylucks** [comment]
Any time estimation on this?
This seems more like a bug than enhancement no?

**Comment by inovua-admin** [comment]
Yes, we're hoping to close it this week

**Comment by inovua-admin** [comment]
Sorry, we've been focusing on fixing rtl-related issues like #17 #21  - had to account for many combinations of scrolling options (we're shipping this soon) and will come back to this issue.

**Comment by inovua-admin** [comment]
Fixed in `4.1.1`

**Comment by inovua-admin** [comment]
We introduced `expandedGroups` and `collapsedGroups` (controlled and uncontrolled) so you can say what you want to have by default (all expanded, so expandedGroups=true; or all collapsed so collapsedGroups=true) - see https://reactdatagrid.io/docs/api-reference#props-expandedGroups

**Comment by goldylucks** [comment]
I don't see it fixed in 4.1.1
same behavior, I open the top level group and all sub groups are being opened as well.
Tried with both calling collapseAllGroups and setting defaultCollapsedGroups.
