### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by robson-fernandes** [inovua/reactdatagrid#181]
Hello,

Would you like to know if the component has support for other languages? If not, is there a way to access the component's labels to translate it?

Thanks

**Comment by msanli220** [comment]
hello,
you can check i18n on the docs .
https://reactdatagrid.io/docs/api-reference#props-i18n

**Comment by msanli220** [comment]
> Hello,
> 
> Would you like to know if the component has support for other languages? If not, is there a way to access the component's labels to translate it?
> 
> Thanks

hello,
you can check i18n on the docs .
https://reactdatagrid.io/docs/api-reference#props-i18n

**Comment by robson-fernandes** [comment]
Thanks!!! :)
