### ISSUE TITLE
🐛 Bugs: Rowspan visual bug when scrolling

### ISSUE THREAD

**Issue by victorhporto** [inovua/reactdatagrid#184]
- what edition are you using - community
- version `4.1.24`

What you did:
Scroll when has rowspan

What happened:
Weird visual bug 

Reproduction repository:
I just reproduce on the [docs page](https://reactdatagrid.io/docs/cell-rowspan-and-colspan)
https://www.loom.com/share/4311a67351e14c6494ad0eb52c1a7c01

Problem description:
All the rowspan config get lost when scroll and the table looks weird

Suggested solution:
Just keep the rowspan visual when scrolling

**Comment by inovua-admin** [comment]
Fixed in `v4.2.4`
