### ISSUE TITLE
 🐛 UNSAFE_componentWillMount/ReceiveProps in Strict mode warnings

### ISSUE THREAD

**Issue by tprebenda** [inovua/reactdatagrid#185]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - 4.1.24

Relevant code or config

``` 
(See screenshots)
```

What you did:
Instantiated an RDG instance following the exact instructions provided in the reference docs

What happened:

![Inovua RDG strict mode](https://user-images.githubusercontent.com/51833623/132744698-162ad30d-d12d-436e-bd9e-04f14d426eb8.PNG)

![Inovua RDG strict mode pt2](https://user-images.githubusercontent.com/51833623/132744702-5485c315-c01c-41f7-bcf2-ce8fcdfdef9f.PNG)

Reproduction repository:

Can't provide code repo, as it is a private repo of my company

Problem description:

Clearly the package is using outdated React code, and the warnings are intimidating, despite no change in functionality.

**Comment by bugigas** [comment]
Any info about the possible update?

**Comment by tprebenda** [comment]
(No unfortunately. Seemingly no one has looked at this ticket yet.)

**Comment by ofehr** [comment]
Also getting this console error. Hopefully resolved soon.

**Comment by mednche** [comment]
I'm getting these console warnings too for `DataGridRow` `InovuaVirtualList`, and `InovuaDataGridCell`. Hope this gets fixed soon.

**Comment by davebrown1975** [comment]
An  up  vote here to have this looked at/resolved. Thanks.

**Comment by thomasgor** [comment]
Any news on that?

**Comment by inovua-admin** [comment]
Fixed in v `5.0.0-canary.1` - stable version `5.0.0` coming soon

**Comment by inovua-admin** [comment]
Fixed in version `5.0.0`.
