### ISSUE TITLE
State update warning

### ISSUE THREAD

**Issue by heibor** [inovua/reactdatagrid#187]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
    in ActiveRowIndicator (created by InovuaVirtualList)

**Comment by inovua-admin** [comment]
Should be fixed in v `5.0.0-canary.1` - stable version `5.0.0` coming soon

**Comment by inovua-admin** [comment]
Fixed in version `5.0.0`.
