### ISSUE TITLE
mousedown events are being swallowed by a grid column group which prevents them from reaching other elements

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#192]
@inovua/reactdatagrid-enterprise@4.1.25

There is a call here:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/Layout/ColumnLayout/HeaderLayout/index.js#L504

that stops events from being propagated. In our code we register for these events globally on a document so that we are notified and can close a modeless popup if a click is done outside of the popup. This code results in the event being swallowed so it never reaches our popup.

It looks like this code is there to make sure dragging a child column group prevents parent column groups from being dragged too but this is already unnecessary as this line:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/Layout/ColumnLayout/HeaderLayout/index.js#L510

will already be true for parent column groups.

So the line #504 can be safely removed.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.27`
