### ISSUE TITLE
How to give line break in  cells?

### ISSUE THREAD

**Issue by msanli220** [inovua/reactdatagrid#197]
It only shows a single line text in rows in grid, however I am trying to display multi line text or give a line break with "/n" but it doesnt give a line break. Any idea or suggestion please?

**Comment by AndreeaStirbu** [comment]
Hi, did you find a solution for this? Thank you!

**Comment by msanli220** [comment]
@AndreeaStirbu  hello, i wrote a css for line break. 
```
.InovuaReactDataGrid__cell__content{
    white-space: break-spaces!important;
    overflow: hidden;
}
```

Also i give a row Height for react data grid component.

**Comment by AndreeaStirbu** [comment]
Thank you for the reply. :) In my case it only works if I set the rowHeight to null, I was hoping there's a way to fit text in cells without using the natural row heights. :(
