### ISSUE TITLE
🐛 Bugs: select all make the selected rows true, but it doesn't change unless I deselect all

### ISSUE THREAD

**Issue by MuhammadSawalhy** [inovua/reactdatagrid#203]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community^4.2.1`

## Relevant code or config

```javascript
<ReactDataGrid
          idProperty="id"
          columns={columns}
          dataSource={dataSourceWraper}
          pagination={true}
          checkboxColumn={true}
          enableFiltering={true}
          defaultFilterValue={filterValue}
          sortable={false} // TODO: implement sorting
          style={{ height: "100%" }}
          selected={true}
          onSelectionChange={({ selected }) => setSelectedRows(selected)}
/>
```

## Problem description

I want to get the selected rows so I use `onSelectionChange`.... when I select all the rows I get the selected rows as `true`, it seems that it is true to indicate that all rows are selected, but when I tried to deselect some rows it sticks to `true`.

Then I set the controlled prop `selected={true}`, I unselected some rows expecting to get all rows selected as `selected` is still `true`.

The selection is not updated until deselect all rows

https://user-images.githubusercontent.com/42011920/139490382-44620bc8-1613-4eab-8b36-88da386f3d6c.mp4

**Comment by yurigenin** [comment]
Not a bug. Read the docs on selected and unselected properties.

**Comment by MuhammadSawalhy** [comment]
> Not a bug. Read the docs on selected and unselected properties. 

Thank you, I am also struggling with refreshing the data of the current page using code. My table uses a remote data source.

**Comment by MuhammadSawalhy** [comment]
> Not a bug. Read the docs on selected and unselected properties. 

Thank you, I am also struggling with refreshing the data of the current page using code. My table uses a remote data source.

**Comment by MuhammadSawalhy** [comment]
> Not a bug. Read the docs on selected and unselected properties. 

Thank you, I am also struggling with refreshing the data of the current page using code. My table uses a remote data source.

**Comment by MuhammadSawalhy** [comment]
> Not a bug. Read the docs on selected and unselected properties. 

Thank you, I am also struggling with refreshing the data of the current page using code. My table uses a remote data source.

**Comment by yurigenin** [comment]
To refresh data when the dataSource is set to a function you need to pass a new function instance:

```const newDataSourceFunction = () => oldDataSourceFunction;```

**Comment by MuhammadSawalhy** [comment]
> To refresh data when the dataSource is set to a function you need to pass a new function instance:
> 
> ```const newDataSourceFunction = oldDataSourceFunction.bind(null);```

Thank you again...
