### ISSUE TITLE
Type definitions for setItemAt and setItemsAt are wrong

### ISSUE THREAD

**Issue by nstoertz** [inovua/reactdatagrid#204]
I'm receiving type errors upgrading to v4.2.2 that look like they are caused by reversing the types of `setItemAt` and `setItemsAt` here: https://github.com/inovua/reactdatagrid/commit/a436372f0bab336387da84c239584d4b3aaf6e0c#diff-0b1026181fd501ec3badf6f47b1016a61392cc5158e32c863a9303223d4e41e0

**Comment by inovua-admin** [comment]
Fixed in `v4.2.3`
