### ISSUE TITLE
Remove Row Active Borders

### ISSUE THREAD

**Issue by AndreeaStirbu** [inovua/reactdatagrid#206]
Is it possible to completly remove the active borders or to control when they appear?

I have tried to use the .InovuaReactDataGrid__row--active class and set the border to none, but that didn't have any effect.

**Comment by inovua-admin** [comment]
You can try to set display none to '.InovuaReactDataGrid__row-active-borders'.

**Comment by AndreeaStirbu** [comment]
Thank you, that solved my issue :)
