### ISSUE TITLE
The 'pageSizes' property is missing from the types definitions

### ISSUE THREAD

**Issue by AlexanderSokolov1** [inovua/reactdatagrid#208]
HI team,

I faced with a compilation error when tried to configure pageSizes for `ReactDataGrid` in typescript.

- what edition are you using - community
- version for `@inovua/reactdatagrid-community` - 4.2.4

Relevant code or config
```
<ReactDataGrid
    columns={props.columns}
    dataSource={dataSource}
    pagination={'remote'}
    pageSizes={[10, 50, 100]} <-- Property 'pageSizes' does not exist on type TypeDataGridProps
/>
```

What you did:
 I tried to configure pagination dropdown with custom set of page sizes.
What happened:
 Compilation error occurred.

Problem description:
Type definitions are incorrect.

Suggested solution:
Add missing property to the `TypeDataGridProps`.

**Comment by inovua-admin** [comment]
Fixed in `4.4.2`
