### ISSUE TITLE
 line focus stroke at rtl direction looks wrong

### ISSUE THREAD

**Issue by art1990** [inovua/reactdatagrid#21]
- what edition are you using - community
- version 4.0.16

What you did: implemented a grid in rtl mode
What happened: line focus stroke at rtl direction looks wrong

<img width="1571" alt="test" src="https://user-images.githubusercontent.com/46848114/104702151-40a32080-571e-11eb-86f3-124609ddd9ea.png">

**Comment by inovua-admin** [comment]
should be fixed in `v4.0.21`

**Comment by art1990** [comment]
thanks, this bugs is fixed
