### ISSUE TITLE
  🐛Inline Edit Not Working After Sorting

### ISSUE THREAD

**Issue by jagf1** [inovua/reactdatagrid#210]
- what edition are you using - community
- version for "@inovua/reactdatagrid-community@^4.1.24"

Relevant code or config

```javascript
```

What you did:

What happened:
After Sorting, the inline edit updated different row.

Reproduction repository:

1. Opened "Grid with inline edit" demo on https://reactdatagrid.io/docs/inline-edit.

2. Sorted by City Name column.
![image](https://user-images.githubusercontent.com/93366417/141877700-518f685c-ebae-4ba4-afe7-a0cb05f73d20.png)

3. Changed "Matthew" to "Matthew - UPDATE" on Name column.
![image](https://user-images.githubusercontent.com/93366417/141877910-0bb71a86-1328-4bd9-a086-c01c699d9843.png)

4. Once moved out from the filed, the update applied to different row.
![image](https://user-images.githubusercontent.com/93366417/141877989-b6eff394-c189-4503-aa47-fea5c4fb7b00.png)

Problem description:
After Sorting, the inline edit updated different row. 

Suggested solution:

**Comment by inovua-admin** [comment]
In the `onEditComplete` method `rowIndex` parameter needs to be replaced with `rowId`. When we have sorting, the cell at the specified id should be updated, id witch can be mixed within the data.

We, also, updated the docs examples: https://reactdatagrid.io/docs/inline-edit
