### ISSUE TITLE
Are there any callbacks for the pager actions?

### ISSUE THREAD

**Issue by AndreeaStirbu** [inovua/reactdatagrid#213]
Is there a way to execute some logic when a user navigates between pages?
In the index.js page I found this logic and I was wondering if we can call gotoNextPage, just like we can call onLimitChange.
![image](https://user-images.githubusercontent.com/33423894/143242741-34ea14ae-df43-40a8-90e4-f70e20a38e4e.png)
I added this line in the ReactDataGrid component:
![image](https://user-images.githubusercontent.com/33423894/143242934-604c1ed8-9a05-4506-8caf-18e194cbdb8a.png)
And I added this callback just for testing, but it's not being called:
![image](https://user-images.githubusercontent.com/33423894/143243024-8d3379bc-5fcb-4231-9671-1b21b4925b27.png)
I see that onSkipChange is triggered when we go to the previous or the next page, but I would like to do different things depending on going backwards, forward or just displaying all the records.
Thank you!

**Comment by msanli220** [comment]
```
  // pagination
    const gotoNextPage= useCallback((paginationProps) => {

        console.log("paginationProps",paginationProps);
       //you can change the limit and skip options here
         
    }, [props])
```
