### ISSUE TITLE
Number of rows showing not updating after changing a Select filter

### ISSUE THREAD

**Issue by riguy14** [inovua/reactdatagrid#216]
What edition are you using: community
Version: 4.5.1 `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` -

Relevant code or config
https://codesandbox.io/s/elastic-wildflower-g7clc?file=/src/App.js

What you did:
Change a filter that **should** result in there being more **rows** showing than the previous filter.

What happened: 
The row data updates but the number of rows showing stays the same until you click elsewhere in the table, then the rest of the rows show up.

Reproduction repository:
https://codesandbox.io/s/elastic-wildflower-g7clc?file=/src/App.js

The Country filter is set to Canada by default. To reproduce, change that filter to United Kingdom and notice that only 3 of the 4 United Kingdom rows show up until you click elsewhere in the table.

Problem description:
The filter is applied to the data, but the number of rows showing doesn't seem to update, so if you should have more rows showing than what is currently showing, you don't see all the data. Also happens when when using multiple=true.

Suggested solution:
It's as if an update/refresh call is being missed after the data is updated. Not sure what the fix would be.

**Comment by inovua-admin** [comment]
Fixed in the previous versions. Check the last version, `5.2.3`.
