### ISSUE TITLE
If multiSelect={false} then pre-setting some rows as being selected does not work. 

### ISSUE THREAD

**Issue by AndreeaStirbu** [inovua/reactdatagrid#217]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community`: 4.5.1

Relevant code or config

The bug can be seen on the documentation site: https://reactdatagrid.io/docs/api-reference#props-selected
If you update the  multiSelect to multiSelect={false}, the row does not look like being selected anymore even though the row still looks to be selected. As you can see, the message still shows "Selected rows: ["1"]" at the top.
![image](https://user-images.githubusercontent.com/33423894/144661423-cd8cf1fe-dcb8-4605-aa83-86e3ce023a82.png)

What you did:
Changed the multiSelect to false to enforce single select.

What happened:
My row that was selected by default when the grid finished loading is not being highlighted.

**Comment by inovua-admin** [comment]
Fixed in `v4.6.0`
