### ISSUE TITLE
Generic Error on the doc e.filterValue.value.localeCompare is not a function

### ISSUE THREAD

**Issue by fstn** [inovua/reactdatagrid#222]
Date range issue, set a start date on the [doc](https://reactdatagrid.io/docs/filtering#range-filters)

 and you get:

![image](https://user-images.githubusercontent.com/2936857/145650480-e64972c9-1baf-4b33-acc6-a77af760f2f0.png)

**Comment by inovua-admin** [comment]
Fixed in `v4.5.4`
