### ISSUE TITLE
Top row duplicating when clicking to expand

### ISSUE THREAD

**Issue by squiral** [inovua/reactdatagrid#223]
enterprise edition
@inovua/reactdatagrid-enterprise": "^4.1.24

What you did:

Clicking  to expand the top row element will result in duplicating the top level of that row again - rather than expanding said row to reveal the second level of drill down in the data

Problem description:

Currently the users will be unable to access the data within the expanded top row.

**Comment by inovua-admin** [comment]
We cannot reproduce this bug, please provide a code sandbox.
