### ISSUE TITLE
Header/Filter row state issues with scrolling and hide options

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [inovua/reactdatagrid#224]
- community 
- `@inovua/reactdatagrid-community: 4.5.7`
-  `react: 16.14`

### Relevant code or config

```TSX
<ReactDataGrid
            theme='default-dark'
            idProperty="id"
            columns={columns}
            dataSource={props.data ? createIds(sanitizeTimestampsFromResults(props.data)) : []}
            style={gridStyle}
            rowHeight={24}
            headerHeight={30}
            defaultFilterValue={filterValue}
            onRowClick={(rowProps) => {
                //console.log(rowProps.data?.optionSymbol);
                if (props?.onSymbolSelect)
                    props.onSymbolSelect(rowProps.data?.optionSymbol);
            }}
        />
```

### What happened:
- On horizontal scroll, especially a bit fast makes the whole header row jumbled up
![image](https://user-images.githubusercontent.com/46624268/147295687-e2534f83-b2b4-4bed-8c7a-48c9409f6537.png)
- On toggling between hide or show filter row, it nothing happens(in below image the row should have been hidden) 
![image](https://user-images.githubusercontent.com/46624268/147295770-95bc2ad4-983c-44c1-b611-bb0b39006668.png)

### A single solution works for both of them for now, If I just do a bit horizontal scroll after the issue. It resets the state and both of them are fixed. It may be due to the state is not handled properly, or some part of my config is causing it to break(these behaviors should by default work irrespective of config)

I have spent a lot of time tinkering with configuration, but nothing seems to fix this, please look into it ASAP

**Comment by inovua-admin** [comment]
Please provide a codesandbox example.

**Comment by muhammad-usman-anwar** [comment]
ok will do
