### ISSUE TITLE
react warning while using version 4.5.7

### ISSUE THREAD

**Issue by muhammad-usman-anwar** [inovua/reactdatagrid#225]
- community 
- `@inovua/reactdatagrid-community: 4.5.7`
-  `react: 16.14`

![image](https://user-images.githubusercontent.com/46624268/147296159-d1e007e1-46c5-48c8-a3fa-bcf7c950b15e.png)

**Comment by halflings** [comment]
I'm getting similar warnings (there's another one above complaining about `gotoPage`).

```Warning: React does not recognize the `gotoPage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `gotopage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.```

Happy to send a PR to fix this if someone has any pointers on what might have caused this regression?

(this wasn't happening in previous versions)

**Comment by AndreeaStirbu** [comment]
I'm also getting the "gotoPage" warning.

**Comment by halflings** [comment]
Maybe this commit will fix this issue, not sure if it's included in the latest release:
https://github.com/inovua/reactdatagrid/commit/e5638f8ca17c417d31c168ee8eb5035926d015b1

**Comment by inovua-admin** [comment]
Fixed in `v4.6.0`
