### ISSUE TITLE
How to add empy space to data row?

### ISSUE THREAD

**Issue by pherm** [inovua/reactdatagrid#228]
- what edition are you using:  community
- version for "@inovua/reactdatagrid-community": "^4.5.9",

What happened: i have a issue with display data in row (data are not separated by a space or empy space)

Suggested solution:
column screenshot -> types -> array of objects -> data server return:
[
  "DEMO MULTIBRAND",
  "DEMO SHOWROOM",
  "DEMO STORE",
  "DEMO TRAVEL",
  "DEMO UP"
]

screenshot:
https://ibb.co/r45yZgS

Thank you for your support

**Comment by inovua-admin** [comment]
The `columns.render` method can be used.
See docs [here](https://reactdatagrid.io/docs/api-reference#props-columns-render).
