### ISSUE TITLE
Responsive Data Grid

### ISSUE THREAD

**Issue by Granddevv** [inovua/reactdatagrid#229]
Hi, I'd like to use the better responsiveness by hiding some columns in mobile view.

Here is the reference link of DevExtreme Table.
[https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/GridAdaptabilityOverview/React/Light/]

![Screen Shot 2022-01-21 at 12 27 42 PM](https://user-images.githubusercontent.com/31965726/150573483-d6e21642-40c8-4a07-83d8-5a99d0a9ca10.png)

How can I use better responsiveness? Please let me know if you have any instructions.

**Comment by inovua-admin** [comment]
You can specify `defaultFlex` at the column level to have responsive columns. And you can use, from the column context menu, `Columns` option from which you can show or hide columns.
