### ISSUE TITLE
stacking-columns doesn't show group row

### ISSUE THREAD

**Issue by ken-murray** [inovua/reactdatagrid#23]
![stacked](https://user-images.githubusercontent.com/47371187/104979650-b2b88580-59fc-11eb-8d8c-f47acfb192de.png)
- what edition are you using - community
- version for `@inovua/reactdatagrid-community` - 4.0.14

What you did: Copied example from: https://reactdatagrid.io/docs/stacking-columns#stacking-columns

What happened: Top column row with group names is not shown.  Grid columns appear like they would using an unstacked column headings grid.

**Comment by inovua-admin** [comment]
Could you share a code snippet?
We assume you're not configuring something correctly - you can take a look at https://codesandbox.io/s/sweet-archimedes-ty42r?file=/src/App.js for a demo

**Comment by ken-murray** [comment]
Using code from: https://reactdatagrid.io/docs/stacking-columns#stacking-columns.  Only tested on Windows 10 Chrome browser.

**Comment by ken-murray** [comment]
Apologies, it Stacked Columns only works on the Enterprise version, not the Community version.  Your documentation at https://reactdatagrid.io/docs/stacking-columns says otherwise.  Changing sandbox code shows issue:

import ReactDataGrid from "@inovua/reactdatagrid-community";
import "@inovua/reactdatagrid-community/index.css";

**Comment by inovua-admin** [comment]
Thanks for bringing this up. Amazing how things get synchronised 🤷‍♂️ Just yesterday we were checking our documentation and spotted the issue that stacking cols is not working in community although it should.
We need to do a bit of code refactor to get this working, as it's somehow related to pivoting as well, which is in enterprise, but we're definitely making this available in community.

**Comment by ken-murray** [comment]
Thanks, that's good to hear :-)

**Comment by inovua-admin** [comment]
Fixed in `4.0.34`
