### ISSUE TITLE
@inovua/reactdatagrid

### ISSUE THREAD

**Issue by narekdanielyan19** [inovua/reactdatagrid#231]
i have data grid created with pagination to be allowed.During rendering it brings  React does not recognize the `gotoPage` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `gotopage` instead. If you accidentally passed it from a parent component, remove it from the DOM element.Anyone can help please? 
 <ReactDataGrid
                groups={groups || []}
                columns={tableState.columns}
                defaultSortInfo={tableState.sortInfo}
                columnOrder={tableState.columnOrder}
                    dataSource
                defaultLimit={10}
                rowHeight={rowHeight || 36}
                showZebraRows
                sortable
                pagination="local"
                // loading={true}
                // pagination
                emptyText={emptyText || 'No records available'}
                columnUserSelect
                multiSelect={multiSelectStatus}
                {...selectable && {
                    // selected={selected}
                    // onRowClick={onRowClick}
                    // toggleRowSelectOnClick={false}
                    checkboxOnlyRowSelect: checkboxOnlyRowSelect || false,
                    enableSelection,
                    onSelectionChange,
                    ...(multiSelectStatus && {
                        checkboxColumn: {
                            headerProps: {
                                className: 'MuiPaper-root colored'
                            },
                            defaultWidth: 50
                            // render: selectBoxRender
                        }
                    })
                }}
                scrollProps={{
                    ...ReactDataGrid.defaultProps.scrollProps
                }}
            />

**Comment by inovua-admin** [comment]
You need to upgrade to version +4.6.0
