### ISSUE TITLE
Resize functionality is not working in mobile view.

### ISSUE THREAD

**Issue by Granddevv** [inovua/reactdatagrid#233]
Resize functionality is not working in mobile view.
![Screen Shot 2022-01-25 at 9 50 30 AM](https://user-images.githubusercontent.com/31965726/150999697-57eee89c-cbe3-40ba-acab-b1e2b48a63da.png)

**Comment by inovua-admin** [comment]
Works fine on a mobile device.

**Comment by Granddevv** [comment]
Yeah it is working on actual mobile device, but it is not working correctly on mobile view of desktop browser.

Can you please let me know what's the reason?
