### ISSUE TITLE
🐛  Late row rendering during scroll. Columns list not scrolling at context menu.

### ISSUE THREAD

**Issue by DaimonX** [inovua/reactdatagrid#234]
- what edition are you using - enterprise
- version for 4.8.3

Relevant code or config

```
const rowHeights = pricatData.reduce((acc: any, next) => {
    acc[next.id] = next.doubleRow ? 70 : 35;
    return acc;
  }, {});
    return (
      <ReactDataGrid
        rowHeights={rowHeights}
        theme="green-light"
        idProperty="id"
        nativeScroll={true}
        checkboxColumn={true}
        checkboxOnlyRowSelect={false}
        onSelectionChange={onSelectionChange}
        defaultFilterValue={columnsFilters}
        loading={isPricatLoading as any}
        columns={columns}
        dataSource={pricatData}
        enableSelection
        style={gridStyle}
        selected={allSelectedRows}
      />
    );
```

What you did:
1st bug. 
Depend on doubleRow I'm changing row height. If row height doubled I'm emulating two rows view at custom render function
What happened:
When I'm scrolling the last rows are rendered too late and I see white space at the end of table. If I remove my dynamic rowHeights everything ok

2nd bug
I have about 50 columns and a thousand rows. When open context menu and try to scroll on columns menu it is not scrolling.

Video:
https://www.loom.com/share/e4c9e9504d614609bada3d087e835840
https://www.loom.com/share/67bf54ebe1944baf9fd2a9a8a00922c3

Codesandbox: 
https://codesandbox.io/s/columns-bug-t1le2?file=/src/App.js

**Comment by inovua-admin** [comment]
@DaimonX 
1. To be able to investigate we need a codesandbox example to demonstrate the issue;
2. In your codesandbox demo make sure the column name is unique https://reactdatagrid.io/docs/getting-started#defining-columns

@RyanTotalEto could you please check the latest version and let us know if the issue still persists?

**Comment by DaimonX** [comment]
> @DaimonX
> 
> 1. To be able to investigate we need a codesandbox example to demonstrate the issue;
> 2. In your codesandbox demo make sure the column name is unique https://reactdatagrid.io/docs/getting-started#defining-columns
> 
> @RyanTotalEto could you please check the latest version and let us know if the issue still persists?

Hello.
Checked on 4.18
Issues are gone. Thank you!
