### ISSUE TITLE
Bug. onBlur does not fire after Context Menu  

### ISSUE THREAD

**Issue by DaimonX** [inovua/reactdatagrid#235]
If click outside grid without Column Context Menu everything ok, but if I click context menu and after that somewhere outside grid onBlur does not fire

Example from your site 
https://reactdatagrid.io/docs/api-reference#props-onBlur

Here video: 
https://www.loom.com/share/74e577b1c348417891ff38cc99668679

**Comment by inovua-admin** [comment]
Fixed in `v4.13.2`
