### ISSUE TITLE
Clicking on Column Context Menu custom option does not close the menu

### ISSUE THREAD

**Issue by AndreeaStirbu** [inovua/reactdatagrid#246]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community` - 4.13.1

I customised the column context menu with a new option. How can I tell the menu to close once I clicked on the option?

The behaviour can be seen on the docs page:
https://reactdatagrid.io/docs/api-reference#props-renderColumnContextMenu
After the click action is executed, the menu context does not close:
![image](https://user-images.githubusercontent.com/33423894/155107415-e315b0f3-2acc-4507-a01a-03785252e472.png)

**Comment by inovua-admin** [comment]
You can add `onDismiss` method from `menuProps` to dismiss the menu. We improve the [example](https://reactdatagrid.io/docs/api-reference#props-renderColumnContextMenu).
