### ISSUE TITLE
Option to allow Multi Select rows without Control/Command/Shift Clicking

### ISSUE THREAD

**Issue by skalidindi** [inovua/reactdatagrid#247]
💡 Feature Requests: 
Allow option for multi selection without requiring command/control clicking. When this option is enabled, clicking on a row will select the row along with all previous rows selected without needing to hold control/command.

**Comment by AndreeaStirbu** [comment]
Did you consider using a checkbox column? :) 
https://reactdatagrid.io/docs/row-selection#multiple-selection-with-checkbox-column

**Comment by skalidindi** [comment]
Thank you that works as a solution. I still think clicking on the row should allow multiple select as well (without needing control/command/shift) through some option like ag-grid allows but clicking on a checkbox works for me meanwhile. Thank you.

**Comment by marcselman** [comment]
I'm looking for this as well.

**Comment by marcselman** [comment]
@skalidindi  It's actually easily done with the following code:
```javascript
const onRowClick = useCallback((rowProps, event) => {
	event.ctrlKey = true;
}, [])
```
and add `onRowClick={onRowClick}` to your grid.
