### ISSUE TITLE
Broken inline editing in latest releases

### ISSUE THREAD

**Issue by petruconst** [inovua/reactdatagrid#248]
- what edition are you usinn: enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 14.13*

Relevant code or config

```javascript
```

What you did:

**What happened:**

Editing cells throws:
framework.a0ed0988326c226543ae.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'rowIndex')

https://imgur.com/a/IELNnam

**Reproduction repository:**

https://reactdatagrid.io/docs/inline-edit -> check anyeditiable fields

**Problem description:**

Inline cell editing is broken

Suggested solution:

**Comment by inovua-admin** [comment]
Fixed in `v4.14.0`.
