### ISSUE TITLE
The recent clipboard feature broke the default browser right click context menu on any cell of the grid

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#249]
This commit below broke the default browser menu on right clicking on any cell of the grid even if the clipboard feature is disabled. You can try the documentation for the clipboard property (default is false) and try to right click on any cell. No browser menu comes up.

https://github.com/inovua/reactdatagrid/commit/001f8d37899800025ab8434fbb855b76ea6d90e1

The issue is that the clipboard plugin add this property:

https://github.com/inovua/reactdatagrid/blob/master/enterprise-edition/plugins/clipboard/index.ts#L16

<img width="680" alt="image" src="https://user-images.githubusercontent.com/11202960/155632490-f1bbe5ce-42c5-428d-8af5-ee3a47a5760e.png">

This line below used to be falsy and the code exited:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/plugins/menus/useMenus/index.ts#L219

<img width="644" alt="image" src="https://user-images.githubusercontent.com/11202960/155632690-33783df3-8c54-4116-bc14-3b7f443fe7c2.png">

Instead, now the flow proceeds to this line below which causes the right hand menu default action to be swallowed if even the clipboard is disabled:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/plugins/menus/useMenus/index.ts#L227

<img width="773" alt="image" src="https://user-images.githubusercontent.com/11202960/155632759-84259a53-f9d2-4c97-b04e-2479e029f216.png">

**Comment by inovua-admin** [comment]
Fixed in `v4.14.1`
