### ISSUE TITLE
Date Editor Broken in latest release

### ISSUE THREAD

**Issue by petruconst** [inovua/reactdatagrid#255]
- _what edition are you using:_ enterprise
- _version for:_ 4.16.2

**What happened:**

Using DateEditor as date component triggers 
      
Uncaught TypeError: matches.call is not a function
    at index.js:24:1
    at curryClosure (curry.js:32:1)
    at DateEditor.componentDidMount (index.js:81:1)

**Reproduction repository:**
https://codesandbox.io/s/crazy-snow-q43wit?file=/src/App.js

**Comment by inovua-admin** [comment]
Fixed in `v4.16.3`
