### ISSUE TITLE
Row Reorder Drag on Touch Devices Exhibiting Inconsistent Behavior

### ISSUE THREAD

**Issue by patrick-y-pokeratlas** [inovua/reactdatagrid#256]
**VERSION**: @inovua/reactdatagrid-enterprise 4.8.3

**ISSUE**: rowReorder drag on touch devices exhibiting inconsistent behavior.

**TESTING ENVIRONMENS**:
- iOS/Safari: works as expected
- Andriod/Chrome: non responsive
- PC/Chrome DevTools device emulation: non responsive

Developing web app that will be primarily used on Android tablets. If there is a way to get a notification on a row reorder touch event, I maybe be able to emulate the desired behavior.

On a related note, the column reorder drag is non responsive (including iOS/Safari).

Please let me know if I can provide additional details. Thank you for your attention.

**Comment by pguidoPokerAtlas** [comment]
It would be nice to get at least some response on this please?  We are paying customer and nothing but crickets so far.  Can you help please?

**Comment by inovua-admin** [comment]
Fixed in v4.19.8

@pguidoPokerAtlas as a paying customer you can always reach us directly. Thanks!

**Comment by pguidoPokerAtlas** [comment]
Hi thank you.  We did reach out directly and never received a reply.
