### ISSUE TITLE
When clicking on any new 'autosize' column menus the column menu does not get hidden

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#258]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - latest

What you did:
Use this example https://reactdatagrid.io/docs/autosize-columns#auto-size-columns and click on any auto-size menus like Autosize to fit, Autoresize this column, or Autoresize all columns.

What happened:
The column menu does not get hidden

Suggested solution:
The issue is that the code for the click handler does not call hideColumnContextMenu function like all other menu handlers do. Instead, it uses menuProps.dismissOnClick = true which is not used by the menu implementation.

**Comment by inovua-admin** [comment]
Fixed in `v4.16.6`
