### ISSUE TITLE
Controlled data source + server side fetching

### ISSUE THREAD

**Issue by offirgolan** [inovua/reactdatagrid#26]
- what edition are you using - enterprise (for evaluation)
- version - 4.0.20

While trying to get inline editing working with infinite scrolling with a remote data source, I noticed that its not really possible since the data source isn't truly controlled. Since the `dataSource` must be method that returns the next set of data, I no longer have access to the entire set of rows since the table component keeps that state internally. For inline editing to actually work with server side data fetching, I'd need full control of the entire data set in order to correctly update the data to the new values.

Ideally, the data source API will be split into 2 different props. `dataSource` which will only be an array, and some sort of `getRows` prop which would be called whenever the table needed a new set of data.

**Comment by inovua-admin** [comment]
Thanks for raising this.
You could try to use [setItemAt](https://reactdatagrid.io/docs/api-reference#method-setItemAt) or [setItemPropertyAt](https://reactdatagrid.io/docs/api-reference#method-setItemPropertyAt) to update the dataSource - since [onEditComplete](https://reactdatagrid.io/docs/api-reference#props-onEditComplete) has the info you need to do the update. Please let us know how this goes - and if you have any issue, it would help to have a code sample to better understand what you are trying to do. Thanks

**Comment by offirgolan** [comment]
`setItemAt` would work for single edits which is great but there are still some other concerns that would be solved if the data source was truly controlled:

1. External changes to the data (e.g. apollo cache updates, websocket events, etc)
2. Needing to share the entire data set with multiple tables, graphs, etc.

You could potentially add a `setItems` method but that would still not be very ideal since we would constantly need to keep the internal data source in sync with the other one (e.g. apollo cache). 

Alternatively you can support an object like dataSource which has the following structure:

```js
{
  data: [],
  getData: () => []
}
```

This would be an additive change to the API without needing a major version bump.

**Comment by inovua-admin** [comment]
Not sure I fully follow your proposal - can you clarify please?
You're suggesting we add an API method to retrieve the currently loaded dataSource? Something like https://reactdatagrid.io/docs/api-reference#method-getItemAt but to retrieve the whole data the grid stores internally?
Or are you proposing the `dataSource` prop accepts a different shape or returns a different object when it's a function?

**Comment by offirgolan** [comment]
Im proposing something like the following:

```js
const columns = [...];

const App = () => {
  const [data, setData] = useState([]);
  const [count, setCount] = useState(0);
  const [loading, setLoading] = useState(false);

  const dataSource = useMemo(() => ({
    data,
    count,
    loadData: ({ skip, sortInfo, limit }) => {
  return fetch(DATASET_URL + '?skip=' + skip + '&limit=' + limit + '&sortInfo='+JSON.stringify(sortInfo))
    .then(response => {
      const totalCount = response.headers.get('X-Total-Count');
      response.json().then((data) => {
        setData(prevData => [...prevData, ...data]);
        setCount(parseInt(totalCount));
      });
    })
}
  }), [data, count])

  return (
    <div>
      <h3>Live pagination example - infinite loading, 50 per page</h3>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        columns={columns}
        pagination
        livePagination
        dataSource={dataSource}
        onLoadingChange={setLoading}
      />
    </div>
  );
}
```

This is just a proposal, I'm sure there are gonna be some other edge cases but doing something like that gives us full control of the data.

**Comment by offirgolan** [comment]
Hi, following up on this since I was able to get this sort of working via bi-directional syncing the internal data source to local state. Unfortunately, the only way to do that is via `onLoadingChange`. 

```js
const dataSource: TypeDataSource = async ({ skip, limit }) => {
  return {
    data: await fetchMockData({ skip, limit }),
    count: 1000
  };
};

const SyncedDataSource = () => {
  const [data, setData] = useState<any[]>([]);
  const [count, setCount] = useState<number>(0);
  const [loading, setLoading] = useState(false);
  const [
    gridRef,
    setGridRef
  ] = useState<MutableRefObject<TypeComputedProps | null> | null>(null);

  useEffect(() => {
    if (gridRef?.current && !isEqual(data, gridRef.current.data)) {
      gridRef.current.setOriginalData(data);
    }
  }, [gridRef, data]);

  return (
    <>
      <Box padding="space1" display="flex" alignItems="center" gap="space1">
        <SecondaryButton
          onClick={() => {
            setData((prevData) => prevData.slice(1, prevData.length));
          }}
        >
          Delete First Row (External)
        </SecondaryButton>
        <SecondaryButton
          onClick={() => {
            setData((prevData) => {
              const [first, ...rest] = prevData;

              return [{ ...first, title: uniqueId('Edit ') }, ...rest];
            });
          }}
        >
          Edit First Row (External)
        </SecondaryButton>
        <SecondaryButton
          onClick={() => {
            gridRef?.current?.setOriginalData([]);
            gridRef?.current?.setSkip?.(0);
          }}
        >
          Reset
        </SecondaryButton>
        <Box flex={1}>
          <Text align="right" bold>
            Showing {data.length} out of {count.toLocaleString()} Productions
          </Text>
        </Box>
      </Box>
      <ReactDataGrid
        onReady={setGridRef}
        columns={columns}
        dataSource={dataSource}
        loading={loading}
        onLoadingChange={(loading: boolean) => {
          if (gridRef?.current && !loading) {
            setData(gridRef.current.data);
            setCount(gridRef.current.count);
          }

          setLoading(loading);
        }}
        pagination
        livePagination
      />
    </>
  );
};
```

I think this solution is _OK_ but depending on the `onLoadChange` callback for data synchronization isn't very intuitive. Another possible solution (if you don't want to go the controlled data source way in my comment above), adding an `onDataSourceChange` callback would be good enough interim solution.

**Comment by inovua-admin** [comment]
Glad to hear you managed to find a solution!
I think an even better solution would be to just pass the current `data` array to the `dataSource` prop.
So besides of having access to skip, limit, etc, you will also have access to `data`

```tsx
const dataSource = ({skip, limit, data }) => {
 return fetch(...).json().then(newData => {
    console.log('full data will be', [...data, ...newData])
    return newData
 })
}

<DataGrid dataSource={dataSource} />
```

**Comment by offirgolan** [comment]
I like that idea as well. I do have 1 question:

If I load 3 pages and `data` has 60 records in it. If I re-sort the table, `data` should be an empty array then correct?

**Comment by inovua-admin** [comment]
Yes, sorting should trigger a full reload of the datasource, so it will reset skip to 0.
Additionally, we have [scrollTopOnSort=true](https://reactdatagrid.io/docs/api-reference#props-scrollTopOnSort), which is what you want most of the time

**Comment by offirgolan** [comment]
Thinking more about this, your proposed solution wouldn't solve the case where the data was manipulated via `setItemAt` or `setItemPropertyAt`. Something like `onDataSourceChange` would better solve this use case.

**Comment by inovua-admin** [comment]
with `v4.0.23` we added the `currentData` property (array) to the object that is being passed in to the `dataSource` function

**Comment by inovua-admin** [comment]
the `currentData` array does include the items changed via `setItemAt` and `setItemPropertyAt`

**Comment by future-mine** [comment]
So pagination is working?
I am using community version.
```
  const dataSource = async ({ skip, limit }) => {
    const searchCriteria = {
      page: skip / limit + 1,
      pageSize: limit
    }
    const data = await apiClient.post(
      "Right/GetPagedRecords",
      searchCriteria
    )
    const result = {
      data: data.data,
      count: data.totalRecords
    };
    console.log('result=================', result)
    return result
  };
```
This is dataSource 
![image](https://user-images.githubusercontent.com/59634187/168233460-86bd6a46-fd1c-4dba-b57b-c7b627b9cbe2.png)
The count is 22 but it shows 10.
