### ISSUE TITLE
Add action columns to rows

### ISSUE THREAD

**Issue by khrishan** [inovua/reactdatagrid#261]
Is it possible to add action rows (in order to delete a row)?

**Comment by noelfloresr** [comment]
Hi, 

What I did was to add a new object in the column array: 

`{
        name: 'action',
        header: 'Action',
        defaultFlex: 1,
        render: (value: any) => {
          return (
            <button
              type="button"
              className="btn btn-blue-transparent"
              onClick={() => {
                handleDetails(value.data.authNumber);
              }}
            >
              View
            </button>
          );
        },
      },`
