### ISSUE TITLE
The last column header is hidden when filtering is added, how can I fix it?

### ISSUE THREAD

**Issue by noelfloresr** [inovua/reactdatagrid#262]
Even in doc example for filtering the last column does not show the header and that creates confusion for users: https://reactdatagrid.io/docs/filtering

I will be so glad you can tell me how can I fix it.

Thanks,

**Comment by inovua-admin** [comment]
We are not able to reproduce. Please provide more details.

**Comment by dbvech** [comment]
They don't saying it, but they already fixed it last versions :)

**Comment by noelfloresr** [comment]
hahaha totally agree, I didn't want to say it, but they did it without accepting it.
