### ISSUE TITLE
How to change the theme color?

### ISSUE THREAD

**Issue by thanimaram** [inovua/reactdatagrid#267]
I'm not see anything related to these things in docs

**Comment by inovua-admin** [comment]
https://reactdatagrid.io/docs/styling-and-theming

**Comment by thanimaram** [comment]
I'm read this document thoroughly, but still not get any idea for to
change that purple color in a table. Plz explain how to change that color
or how to remove that one.
   Thank you

**Comment by ousadojunplid** [comment]
hey @shorif2000 , Were you able to edit the theme? I have the same problem of not being able to change the dark color.
