### ISSUE TITLE
how to change the purple color to another color in table

### ISSUE THREAD

**Issue by thanimaram** [inovua/reactdatagrid#269]
read full docs, but still not  find a proper method, plz suggest any method to resolve that one

![Screenshot (243)](https://user-images.githubusercontent.com/91260194/165692402-da252681-b801-493e-b910-314538fb6020.png)

**Comment by marcselman** [comment]
The 5 colors that you see in the demo are different themes.
It's documented at the bottom of this page: https://reactdatagrid.io/docs/styling-and-theming

**Comment by inovua-admin** [comment]
@marcselman we'll write a tutorial to explain how to create custom themes

**Comment by inovua-admin** [comment]
Fixed in version `5.2.3`. See the [article](https://reactdatagrid.io/docs/styling-and-theming#creating-your-own-theme) for creating a custom theme.
