### ISSUE TITLE
When I used index.css with webpack LICENSE file in the root directory of this source tree.

### ISSUE THREAD

**Issue by muazcoban** [inovua/reactdatagrid#276]
- version for `@inovua/reactdatagrid-enterprise`
"@inovua/reactdatagrid-enterprise": "^4.19.3",
Relevant code or config

```javascript
import ReactDataGrid from '@inovua/reactdatagrid-enterprise';
import '@inovua/reactdatagrid-enterprise/index.css';

<ReactDataGrid
  loadNode={loadNode}
  {...props}
  licenseKey="mylicenseKey"
  idProperty="id"
  columns={gridColumns}
  style={gridStyle}
  defaultExpandedNodes={defaultExpandedNodes}
  stickyTreeNodes={stickyTreeNodes}
/>
```

Problem description:

I have a license key but when I used "import '@inovua/reactdatagrid-enterprise/index.css';"  I get error 
"You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * LICENSE file in the root directory of this source tree."

<img width="781" alt="image" src="https://user-images.githubusercontent.com/34477839/167877643-a257dcfc-4118-43e7-a89c-18fe0bbaa6c1.png">

**Comment by inovua-admin** [comment]
This seems to be a webpack misconfiguration
