### ISSUE TITLE
InovuaVirtualList component error

### ISSUE THREAD

**Issue by acetine63** [inovua/reactdatagrid#279]
This is the error I am getting when I try to mount a simple react-data-grid component.
Until the component is loaded, the application runs fine.

Code Sandbox code is: 
[Code Sanbox](https://codesandbox.io/embed/infallible-grass-3xregc?fontsize=14&hidenavigation=1&theme=dark)

Code Sanbox code:
```
import React from "react";
import ReactDataGrid from "@inovua/reactdatagrid-community";
import "@inovua/reactdatagrid-community/index.css";

const gridStyle = { minHeight: 550 };

const columns = [
  { name: "id", header: "Id", defaultWidth: 80, defaultVisible: false },
  {
    name: "name",
    sortable: false,
    header: "Name (column not sortable)",
    defaultFlex: 1
  },
  { name: "age", header: "Age", type: "number", defaultFlex: 1 }
];

const dataSource = [
  { name: "Little Johny", age: 8, id: 0 },
  { name: "John Grayner", age: 35, id: 1 },
  { name: "Mary Stones", age: 35, id: 2 },
  { name: "Robert Fil", age: 17, id: 3 },
  { name: "Bob Margin", age: 17, id: 4 },
  { name: "Hillary Wilson", age: 53, id: 5 },
  { name: "Franklin Richardson", age: 37, id: 6 }
];

const App = () => {
  return (
    <ReactDataGrid
      idProperty="id"
      style={gridStyle}
      columns={columns}
      dataSource={dataSource}
    />
  );
};

export default () => <App />;


```

The error is;

The above error occurred in the <InovuaVirtualList> component:
    at InovuaVirtualList (http://localhost:3000/static/js/bundle.js:71054:34)
    at InovuaDataGridList (http://localhost:3000/static/js/bundle.js:6066:34)
    at FakeFlex (http://localhost:3000/static/js/bundle.js:2133:34)
    at div
    at InovuaDataGridColumnLayout (http://localhost:3000/static/js/bundle.js:14519:34)
    at FakeFlex (http://localhost:3000/static/js/bundle.js:2133:34)
    at div
    at InovuaDataGridLayout (http://localhost:3000/static/js/bundle.js:15305:34)
    at div
    at http://localhost:3000/static/js/bundle.js:18086:41
    at TheGrid (http://localhost:3000/static/js/bundle.js:19527:43)
    at div
    at ViewTable (http://localhost:3000/static/js/bundle.js:815:5)
    at App

**Comment by inovua-admin** [comment]
@acetine63 it seems you are using the component in strict mode. The component works as expected if you remove the strict mode. We are working on a fix. We'll keep you posted.
