### ISSUE TITLE
setColumnSizesToFit is always undefined

### ISSUE THREAD

**Issue by jdkealy** [inovua/reactdatagrid#280]
Hello, I would like my grid to fill the space. I set `enableColumnAutosize` to true and even added a click handler like in the docs. 
I'm using `7.0.0-beta.13`. The function is  just never defined in `gridRef.current.setColumnSizesToFit()`

- what edition are you using - community / enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` -

Relevant code or config

```javascript
```

What you did:

What happened:

Reproduction repository:

Problem description:

Suggested solution:

**Comment by inovua-admin** [comment]
@jdkealy please provide a codesandbox sample to better understand your issue. Also, our latest version is `4.19.5`  not `7.0.0-beta.13`.
