### ISSUE TITLE
if using pagination select all check box was not working

### ISSUE THREAD

**Issue by thanimaram** [inovua/reactdatagrid#281]
if using pagination select all check box was not working, 
![Screenshot (265)](https://user-images.githubusercontent.com/91260194/170504996-a65d1bff-b0ea-49e1-81da-c606c39d4a48.png)

**Comment by inovua-admin** [comment]
We updated the example from [docs](https://reactdatagrid.io/docs/row-selection#multiple-selection-with-checkbox-column). You can use `data` parameter from `onSelectionChange` callback.
