### ISSUE TITLE
how i can remove border color?

### ISSUE THREAD

**Issue by NuengTomorrow** [inovua/reactdatagrid#282]
i use @inovua/reactdatagrid-community 
how i can remove border color 
![Screen Shot 2565-06-01 at 14 30 47](https://user-images.githubusercontent.com/60811285/171351871-cf9177cc-6b56-47f0-9433-300451146d56.png)

**Comment by eddie** [comment]
This can also be done with

```
			showHoverRows={false}
			showActiveRowIndicator={false}
```
