### ISSUE TITLE
Uncaught TypeError: _this.rows is null

### ISSUE THREAD

**Issue by mirceamat** [inovua/reactdatagrid#288]
"dependencies": {
    "@inovua/reactdatagrid-community": "^4.20.0",
    "@reduxjs/toolkit": "^1.8.3",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^14.2.1",
    "@types/jest": "^28.1.3",
    "@types/node": "^18.0.0",
    "@types/react": "^18.0.10",
    "@types/react-dom": "^18.0.5",
    "antd": "^4.21.4",
    "date-fns": "^2.28.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-json-view": "^1.21.3",
    "react-redux": "^8.0.2",
    "react-scripts": "^5.0.1",
    "typescript": "^4.7.2",
    "web-vitals": "^2.1.4"
  },

"Uncaught TypeError: _this.rows is null
    InovuaVirtualList index.js:855
    InovuaVirtualList index.js:868
    UNSAFE_componentWillReceiveProps index.js:1548"

"The above error occurred in the <InovuaVirtualList> component:
InovuaVirtualList@http://localhost:3000/static/js/bundle.js:64388:34
InovuaDataGridList@http://localhost:3000/static/js/bundle.js:12699:34
FakeFlex@http://localhost:3000/static/js/bundle.js:8766:34"

For the basic example i get the above error "Uncaught TypeError: _this.rows is null"

**Comment by inovua-admin** [comment]
@mirceamat, we are currently working with high priority to provide support with react 18.

**Comment by nhope123** [comment]
I am currently facing the same issue. Is the support for 18 now in place?

**Comment by levz0r** [comment]
Any ETA guys?

**Comment by RoySegall** [comment]
Shall I be dammed 😢 I'm trying to use this one with next and got a hydration issue which their documentation helped but I got the 

> Cannot read properties of null (reading 'length')

when copying the example one to one. Now, I can see there's an issue with react 18. I think until you'll fix the issue you need to throw an error about an un-supported react version.

**Comment by petruconst** [comment]
Any news on this issue?

**Comment by drewwyatt** [comment]
I'm also seeing this using the example from the readme.

**Comment by inovua-admin** [comment]
Fixed in version `5.0.0`.
