### ISSUE TITLE
Possibility to disable row/s and checkbox selection of enabled row/s only

### ISSUE THREAD

**Issue by vishal-kadmos** [inovua/reactdatagrid#289]
I am in a situation where I need to show data grid with checkbox row selection for rows and need to exclude disabled rows from selection

- what edition are you using - **community** 
- version for `@inovua/reactdatagrid-community` - **4.19.8**

What happened:
- I was exploring documentation for provision to disable specific row/s but I didn't find any.
- Allow checkbox bulk row selection(works perfect 👏 ) but should exclude `selected` ids for disabled rows. 

Problem description:

- I was exploring documentation for provision to disable specific row/s but I didn't find any.
- Allow checkbox bulk row selection(works perfect 👏 ) but should exclude `selected` ids for disabled rows. 

@inovua-admin Would it be possible to provide this feature in community edition? Thanks

**Comment by inovua-admin** [comment]
Fixed in version `5.3.0`.

**Comment by teja-centime** [comment]
@vishal-kadmos  Hi Vishal, how do you pass the disabled rows or mark a row as disabled ? I dont see anything in documentation. Can you please provide a description on the usage or link for me to refer. Thank you very much.

**Comment by vishal-kadmos** [comment]
One solution is to use `isRowSelectable` and pass is flag for each row when row data is provided for grid. 
https://mui.com/x/react-data-grid/row-selection/#disable-selection-on-certain-rows

**Comment by teja-centime** [comment]
@vishal-kadmos  You've given me the link for Mui-Datagrid, not this current datagrid - https://reactdatagrid.io/
Can you check ?
