### ISSUE TITLE
🐛 Column menu jumps on the top left of the screen

### ISSUE THREAD

**Issue by J3ffx** [inovua/reactdatagrid#290]
I am using community edition
version for `@inovua/reactdatagrid-community` : 4.6.2

- Open https://reactdatagrid.io/demo
- Open column context menu on Phone column
- Deselect Phone column from the list of displayed columns
- While keeping the context menu open, scroll down the table with the mouse wheel 

result: the menu jumps on the top left of the screen

**Comment by inovua-admin** [comment]
Fixed in v `5.0.0-canary.1` - stable version `5.0.0` coming soon

**Comment by inovua-admin** [comment]
Fixed in version `5.0.0`.
