### ISSUE TITLE
Date filtering is based on wrong format

### ISSUE THREAD

**Issue by mednche** [inovua/reactdatagrid#292]
- What edition are you using - community
- Version for `@inovua/reactdatagrid-community`: 4.19.5

**Relevant code or config:**

```javascript
const cols = [
		{
			name: 'date_submitted',
			header: 'Date',
			type: 'date',
			defaultFlex: 1,
			minWidth: 400,
			filterEditor: DateFilter,
			filterEditorProps: (props, { index }) => {
			  // for range and notinrange operators, the index is 1 for the after field
			  return {
				dateFormat: 'D/M/YY',
				cancelButton: false,
				highlightWeekends: false,
				placeholder: index == 1 ? 'Date is before...': 'Date is after...'
			  }
			},
			render: ({ value, cellProps }) => {
			  return moment(value).format('D/M/YY')
			}
		  }
]

const filters = [
		{
			name: "date_submitted",
			operator: "inrange",
			type: "date",
			value: "",
		},	
	];
```

**What you did:**
I tried to implement the date range filtering (inrange) with the code above. My dates are formatted with moment to follow the UK format D/M/YY.

**What happened:**
The dates appear to be formatted correctly in both the filter bar and the table (e.g. 2022-05-21T14:39:03.886Z => "21/5/22") but the filtering does not work as expected. 

For example, rows with a date of "21/5/22" are included when "date is after" is the 1st, 2nd, 3rd, 4th or 5th of any month (e.g. "1/7/22"). It appears to confuse the first (day) and second (month) terms of the date format (D/M/YY). 

I imagine this is something to do with the fact that I'm using a UK date format instead of the US (M/D/YY) one?

**Comment by mednche** [comment]
Any update on this issue?

**Comment by inovua-admin** [comment]
You should specify the `dateFormat` on the column as well.

```js
const col = {
      dateFormat: 'D/M/YY', // make sure you also specify this
 
     name: 'date_submitted',
    header: 'Date',
    type: 'date',
    defaultFlex: 1,
    minWidth: 400,
    filterEditor: DateFilter,
    filterEditorProps: (props, { index }) => {
   }, 
   render: ({ value, cellProps }) => {
     return moment(value).format('D/M/YY')
   }
```

**Comment by mednche** [comment]
Thanks @inovua-admin, it worked!
