### ISSUE TITLE
 🐛 Bugs: Filtering and pagination doesn't work together.

### ISSUE THREAD

**Issue by fstn** [inovua/reactdatagrid#3]
Trying to use pagination and filtering together, it doesn't work as you can see on this screen the total count and the number of pages are false. 
 

 `@inovua/reactdatagrid-community`

![image](https://user-images.githubusercontent.com/2936857/96649397-a71ecb00-12f6-11eb-801e-a59ed06f4be0.png)

**Comment by inovua-admin** [comment]
Thank you for your report! We appreciate taking the time to submit it, but we kindly ask that you follow the bug report guildelines found in the new issue template - https://github.com/inovua/reactdatagrid/issues/new

>   **ISSUES WITHOUT REPRODUCTION CODE WILL BE CLOSED ** - make sure you create a reproduction example or repo with create-react-app, either as a standalone repo or a codesandbox example

As such, we need a standalone example repo or codesandbox example.

**Comment by fstn** [comment]
As you can see on the screenshot, you just have to add pagination on the filtering example.

Very easy to reproduce:
[](https://codesandbox.io/s/loving-hermann-tsmjn?file=/src/flags.tsx)

**Comment by inovua-admin** [comment]
Thank you for the complete example - it does help us and sets a good pattern for next issues.
A fix is in the works, and we'll update the issue when a new version is released.

It's indeed a bug - although the combination is not very usual. Usually pagination is used in combination with remote data - so `dataSource` would be a function that returns a promise resolving to an array.

**Comment by inovua-admin** [comment]
This should now be fixed in v `4.0.4` - so `4.0.4` not 404 😂

**Comment by fstn** [comment]
Thanks it worked ;)
Stephen ZAMBAUX

0680114469


Le ven. 23 oct. 2020 à 03:51, inovua-admin <notifications@github.com> a
écrit :
