### ISSUE TITLE
Last column Date Filter :  Calendar is truncated

### ISSUE THREAD

**Issue by marquetd** [inovua/reactdatagrid#30]
Edition `@inovua/reactdatagrid-community

Relevant code or config

just take an example with a date filter column

What you did:
Put the date column at the end of the grid
The grid fill the body space.

What happened:

The calendar is hidden

![image](https://user-images.githubusercontent.com/1841731/106287138-c064db00-6246-11eb-9939-fec9e439f3fb.png)

**Comment by anhba817** [comment]
Hi,
The issue still happens in case we are using inrange/notinrange operator, for the end Editor.
Could you please apply the fix for it also?
Regards,
Dong

**Comment by radamesh** [comment]
Hi,

this issue was not resolved in editable mode.

**Comment by radamesh** [comment]
have you try to use a new version?

**Comment by radamesh** [comment]
Hi @mednche By the time I questioned it, they should have fixed it. In this case, it is better to open another issue.

Hi @inovua-admin, could you help us ?
