### ISSUE TITLE
The filter icon requires a double click after clicking once to display the filter context menu.

### ISSUE THREAD

**Issue by sumancelestial** [inovua/reactdatagrid#300]
The filter icon requires a double click after clicking once to display the filter context menu.

Each column can have a filter icon and after clicking it the filter context menu would be displayed.

But here I am facing one issue when I click on the filter icon of the particular column, the filter context menu would be displayed, after displaying the menu if you click anywhere on the grid, the filter context menu would be closed. Now if you want to display the filter context menu of the same column(previous one) again, it requires a double click on a filter icon.

This can be reproduced at the demo site (https://reactdatagrid.io/demo) as well.

I have recorded the video of the issue being reproduced.

[double-click-filter.webm](https://user-images.githubusercontent.com/91245812/186613783-90c3f3c6-79c7-494d-b060-408294469cec.webm)

**Comment by inovua-admin** [comment]
Fixed in v `5.0.0-canary.1` - stable version `5.0.0` coming soon

**Comment by inovua-admin** [comment]
Fixed in version `5.0.0`.
