### ISSUE TITLE
💡❓ Receiving an object in column name

### ISSUE THREAD

**Issue by brunofilho1** [inovua/reactdatagrid#305]
- version for `@inovua/reactdatagrid-community` 

I'm getting an object that contains the value I need to insert into the column, so far so good, I'm accessing it like this in the construction of the columns object:

```javascript
{
      name: 'Anexo',
      header: 'Projeto',
      render: ({ value }) => {
        const { IdJob } = value
        return <p title={IdJob}>{IdJob}</p>
      },
},
```

However, if I want to have 2 columns that consume different values ​​from the same object, I have an error of columns with equal id. What can I do in this case?

For example:

```javascript
{
      name: 'Anexo',
      header: 'Projeto',
      render: ({ value }) => {
        const { IdJob } = value
        return <p title={IdJob}>{IdJob}</p>
      },
},
{
      name: 'Anexo',
      header: 'Name',
      render: ({ value }) => {
        const { name } = value
        return <p title={name}>{name}</p>
      },
},
```

![image](https://user-images.githubusercontent.com/79478204/194935546-254a435b-a28d-4594-8cc6-cd40b4c40291.png)

My dataSource is something like this:

```javascript
{
      {...},
      {...},
      {...},
      {
        Anexo: {
           name: 'Anexo',
           header: 'Projeto',
           render: ({ value }) => {
             const { IdJob } = value
             return <p title={IdJob}>{IdJob}</p>
           },
        },
        review: "test-review",
        id: 45,
        title: "testing the datagrid"
      },
},
```

💡 If there is no way, I suggest this as a new feature!

**Comment by inovua-admin** [comment]
Every column is uniquely identified by its `id`. If you don't specify an `id`, the column will be identified by its `name`. So, you cannot have two columns with the same `id`. If you have the same `name`, specify a diferent `id` to the column.
