### ISSUE TITLE
 The last column of the table is truncated

### ISSUE THREAD

**Issue by art1990** [inovua/reactdatagrid#31]
- what edition are you using - community or enterprise
- version 4.0.22
- macos, Google Chrome   ver 88.0.4324.96 , (x86_64)

What you did: implemented a grid in **rtl**  or **ltr** mode
What happened:  When table is **scrollable**, the last column of the table is truncated
<img width="1051" alt="Снимок экрана 2021-02-01 в 08 40 20" src="https://user-images.githubusercontent.com/46848114/106423978-19608900-646a-11eb-99e5-cb5b6fb43fd1.png">

**Comment by inovua-admin** [comment]
![Screenshot 2021-02-02 at 00 23 10](https://user-images.githubusercontent.com/72134617/106525559-d72c5b80-64ec-11eb-83c6-360813ae2a0c.png)

Thanks for reporting. Could you share a bit more info on this one? As we're not able to reproduce. 
We did try the same example - the one found here https://reactdatagrid.io/docs/filtering#filtering
Also, it's worth knowing scrolling preferences in MacOS -> system preferences -> general -> show scrollbars.
Do you have it set to always or when scrolling? Did you make any other changes to the grid?
Can you reproduce this with v `4.0.20`? As we did do some fixes for RTL in v `4.0.21`, which could potentially affect this.
Also worth building a more simple version of the grid, give it a fixed width, and give columns a bigger width, so it has scrollbars by default and see if it reproducible there.

Thanks for your support - really appreciate! 🙏

**Comment by art1990** [comment]
- v 4.0.20 - reproduced it
- scrollbars preferences - screenshot bellow
- (https://reactdatagrid.io/docs/filtering#filtering) for reproduce this problem, we must have horizontal scroll. I added a few columns in "columns" props and removed "**defaultFlex**" props **from each column** and then appeared horizontal scroll bar => the last column is truncated
<img width="777" alt="Снимок экрана 2021-02-04 в 10 00 45" src="https://user-images.githubusercontent.com/46848114/106863284-f1269380-66d0-11eb-9c26-16c324dec067.png">
