### ISSUE TITLE
Open Menu on Click (left mouse button)

### ISSUE THREAD

**Issue by JoshClose** [inovua/reactdatagrid#310]
- what edition are you using - community / enterprise

community

- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` -

5.3.0

I would like the capability to show a menu on a click.

**Comment by inovua-admin** [comment]
@JoshClose https://reactdatagrid.io/docs/context-menu-integration

**Comment by JoshClose** [comment]
As far as I can tell this is only on a right click. I would like to be able to do this on left clock also.
