### ISSUE TITLE
Switching from range filter to comparison filter does not clear input properly

### ISSUE THREAD

**Issue by AndrewBoklashko** [inovua/reactdatagrid#313]
Steps to reproduce:

- open demo website: https://reactdatagrid.io/demo
- change `Salary` filter operator to "In range"
- fill start and end with any values
- switch back to "Greater than" filter
- click on "Salary" filter input

Expected result:
![image](https://user-images.githubusercontent.com/15115317/197729861-52a7cd1f-9d3d-4e7c-b814-57f14d432588.png)

Actual result:
![image](https://user-images.githubusercontent.com/15115317/197729604-d53a8411-fc12-4b6f-8a7b-5276c97c0ad4.png)

**Comment by inovua-admin** [comment]
Fixed in version `5.5.0`.
