### ISSUE TITLE
In range date filters displaying faulty dates

### ISSUE THREAD

**Issue by MichielBienkens** [inovua/reactdatagrid#314]
Version:

"@inovua/reactdatagrid-community": "^5.6.0",

What I did:

I'm filtering the datagrid, using the DateFilter as the filter editor. I'm changing the date filter to 'In range', making the start and end date picker visible. When filling in the start date, the end date is also displayed already, but the value is not set in the filter. When selecting the end date, both the start date field and the end date field now display the end date. The filter value is still correct, but just not displayed correctly. My data is filtered correctly.

What happened:

![image](https://user-images.githubusercontent.com/32295882/200795131-4510c4a6-b24f-403f-b5e9-2fa242f209db.png)

Reproduction repository:

This can be reproduced here: https://reactdatagrid.io/docs/filtering#filtering 
The example is currently having the same issue.

Reproduction steps:
- Change Birthdate filter to 'In range'
- Set the start date
- Set the end date
- Both date fields show the end date.

The start and end date should be displayed correctly.

**Comment by riguy14** [comment]
+1

**Comment by 01edie** [comment]
+1

**Comment by andrei8888** [comment]
I have this issue too. Can anyone handle this please?

**Comment by Braggedtooth** [comment]
any updates on this?

**Comment by marcselman** [comment]
Yeah, this issue should be picked up. The date range filter is basically unusable.

**Comment by inovua-admin** [comment]
Fixed in version `5.8.2`.
