### ISSUE TITLE
🐛 Getting filtered rows throws exception

### ISSUE THREAD

**Issue by fly-robin-fly** [inovua/reactdatagrid#317]
I already had issue #311, but it was closed before I had a chance to discuss.

I'm trying to get the filtered rows. This works fine until I add my own filter types.

Sandbox:
https://codesandbox.io/s/reactdatagrid-filter-issue-jhhh7u?file=/src/App.js

Steps to reproduce the issue:
1. Open the link to the sandbox
2. Try any of the available filters (should work perfectly, and the filtered rows will be printed to the console)
3. Activate line 68
4. Now change any filter value (this should end in an exception)

I only have this problem when adding own filter types. The code is copied from multiple examples from your website. Please let me know if this is a bug or if there is a workaround

**Comment by inovua-admin** [comment]
Fixed in verison `5.8.1`.
