### ISSUE TITLE
💡 Feature Request : Local Filtering with Remote Data

### ISSUE THREAD

**Issue by Azrideus** [inovua/reactdatagrid#319]
Hello , I want to have remote data ( passing function as dataSource ) and still be able to use local filtering option
but when I use a remote datasource it automatically switches to remoteFiltering

can we have a prop for each column and one for the entire grid that specifies filtering mode?

**Comment by Azrideus** [comment]
I noticed there is a undocumented remoteFilter prop, but it has no effect

**Comment by yurigenin** [comment]
If you think about it, it goes against the common sense. Think about the user interface for a minute if such behavior existed. Remote data source mode assumes that you retrieve data page by page. Now, say you retrieved first page and local filter for a column filters out all rows in that page. User will see an empty screen even though there is more data on the server!

**Comment by Azrideus** [comment]
I guess you are correct 
 but I ran into a case where there are only like 80 rows on the server and it all fits into a single page
 when the user tries to use the filtering feature the app sends a request to the server again, even though my app already has all the data of the server and should be able to filter the data locally,
 
 so I wanted to make a feature that detects if there are less than one page of data on the server and disable the remote filtering on the fly

**Comment by yurigenin** [comment]
In that case, why use remote data source at all? Just use the local data source and in the onComponentMount method retrieve all data at once.

**Comment by Azrideus** [comment]
> In that case, why use remote data source at all? Just use the local data source and in the onComponentMount method retrieve all data at once.

The user first selects a shop then enters a new page to see all of its products so I wouldnt know how many rows the selected shop has

> If you need to support both then determine which one is required in the onComponentMount and then toggle remote vs local mode.

Oh yes, I guess I can detect that and switch between local and remote that way,
Thanks for your help 👍
