### ISSUE TITLE
TreeGrid issue with row re-order

### ISSUE THREAD

**Issue by Sudarsanam-Krishnan** [inovua/reactdatagrid#322]
Please Refer to example codesandbox on -> https://reactdatagrid.io/docs/api-reference#props-enableTreeRowReorder

Steps to recreate
1. Drag "iMovie" row upward and drop it on "App Store" row.  Intent is to move this row above "App Store" row

Expected Behaviour:  App Store and iMovie row gets swapped
Actual Behaviour: iMovie row disappears from grid

**Comment by inovua-admin** [comment]
Fixed in verison `5.8.1`.
