### ISSUE TITLE
onRenderRow props not found.

### ISSUE THREAD

**Issue by SampathkumarSadasivam** [inovua/reactdatagrid#34]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` -4.0.22

Relevant code or config
 import React from 'react'
import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 }

const onRenderRow = ({ data, style }) => {
  const { age } = data
  if (age > 30) {
    if (age > 35) {
      style.color = '#ef9a9a'
    } else {
      style.color = '#7986cb'
    }
  }
}

const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, defaultWidth: 80 },
  { name: 'name', header: 'Name', defaultFlex: 1 },
  { name: 'email', header: 'Email', defaultFlex: 1 },
  { name: 'country', header: 'Country', defaultFlex: 1,
    render: ({ value }) => flags[value] ? flags[value] : value
  },
  { name: 'age', header: 'Age', type: 'number', defaultFlex: 1 }
]

const App = () => {
  return (
    <div>
      <div style={{marginBottom: 20}}>
        Customized row rendering, computed by age
      </div>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        onRenderRow={onRenderRow}
        columns={columns}
        dataSource={people}
      />
    </div>
  );
}

export default () => <App />

What you did:

What happened:
Not found when we try.

Reproduction repository:

Problem description:

Suggested solution:

**Comment by inovua-admin** [comment]
`onRenderRow` is working correctly - see https://codesandbox.io/s/wonderful-hamilton-ch0gr

**Comment by SampathkumarSadasivam** [comment]
Still am getting error.

![image](https://user-images.githubusercontent.com/65353718/107313351-5951ec80-6ab8-11eb-93d1-d6e67172a8b9.png)

**Comment by AndrewBoklashko** [comment]
@inovua-admin I am running into this as well, please reopen this issue.
![image](https://user-images.githubusercontent.com/15115317/188112016-56535e05-6b36-4f6a-b75f-2afe3b4a286a.png)

**Comment by dave-multiplier** [comment]
Same issue here @inovua-admin 
`onRenderRow` does not exist in the prop type definitions.
Could you please add it? 

![image](https://user-images.githubusercontent.com/88761324/191424758-4c30f706-b05c-4b90-b0ae-b2d2fdbb167d.png)

**Comment by treece** [comment]
What's the status with this issue? I'm getting the same type error.
