### ISSUE TITLE
  🐛 Bugs: License Key not Sent

### ISSUE THREAD

**Issue by Dorcy64** [inovua/reactdatagrid#349]
Hi team, 

I have bought an enterprise license but haven't received any code or invoice in my email. Can you please double-check the subscriptions or support emails?

**Comment by inovua-admin** [comment]
@Dorcy64 it seems you used a different email address. The license should be already in your inbox.

**Comment by Dorcy64** [comment]
Can you please double-check that the email was sent to finance@gnosiscompanies.com

**Comment by inovua-admin** [comment]
The license key was sent to the email used for purchase (finance@gnosisf******.com).
