### ISSUE TITLE
Filling datasource from Redux in Remote pagination and remote data mode

### ISSUE THREAD

**Issue by arianshahalami** [inovua/reactdatagrid#35]
I'm using Redux, Redux Saga and Reactdatagrid version 4.0.22. The problem is dataSource prop only supports an array or a promise/function as value. So when I pass an array of data from Redux to dataSource, how can I set the count (total results) to the component?? both the data and pagination are remote.

**Comment by inovua-admin** [comment]
You can easily create a function that returns the data array and a count.

```
const dataSource = useCallback(() => Promise.resolve({ data: data, count: remoteCount }), [remoteCount, data])
```

**Comment by inovua-admin** [comment]
With v `4.0.23` which fixes some edge cases with dataSource loading, it should be even better. We'll close this but feel free to reopen if you think your problem is not fixed
