### ISSUE TITLE
Date filter icon in "rtl mode" doesnot have horizontal padding

### ISSUE THREAD

**Issue by art1990** [inovua/reactdatagrid#36]
- community v 4.0.22

What you did: implemented a grid in rtl mode
What happened: date filter icon doesnot have horizontal padding
<img width="204" alt="Снимок экрана 2021-02-09 в 08 01 55" src="https://user-images.githubusercontent.com/46848114/107322522-4d146200-6aad-11eb-8101-630bccd08ac7.png">

**Comment by inovua-admin** [comment]
Fixed
