### ISSUE TITLE
is renderRow prop removed or renamed?

### ISSUE THREAD

**Issue by MohammadxAli** [inovua/reactdatagrid#41]
Hi, thanks for your great plugin. I'm using enterprise version `@inovua/reactdatagrid-enterprise@4.0.23`, seems like **renderRow** property is missing but it is [documented in the API docs](https://reactdatagrid.io/docs/api-reference#props-renderRow)

Here's a sandbox: https://codesandbox.io/s/eloquent-brattain-t954x?file=/src/App.tsx

```
Property 'renderRow' does not exist on type 'IntrinsicAttributes & Pick<TypeDataGridProps, "style" | "filterable" | "onReady" | "handle" | "renderInPortal" | "onSkipChange" | ... 160 more ... | "isRowReorderValid"> & Partial<...> & Partial<...>'
```

What I'm basically trying to do is to change the background color of each row based on some specific data, I thought that renderRow does the trick, is it removed from API or renamed, or maybe you can purpose a solution on doing something similar with another method or callback prop. Thanks in advance.

**Comment by inovua-admin** [comment]
Fixed in `4.0.25`
