### ISSUE TITLE
Text input clear button submits wrapping form

### ISSUE THREAD

**Issue by andrewhawk1ns** [inovua/reactdatagrid#42]
- what edition are you using - community
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - 4.0.16

Relevant code or config

```  <div
        key="clearButton"
        className={join(
          `${rootClassName}__clear-button-wrapper`,
          !showButton && `${rootClassName}__clear-button-wrapper--hidden`
        )}
      >
        {this.renderClearButton({
          clearButtonColor,
          clearButtonStyle,
          clearButtonSize,
          ...getClearButtonClassNames(props),
        })}
      </div>
```

What you did:

My data grid runs in tabs which are wrapped in a form. 

What happened:

When I type something in the filter text box and then press the clear button it bubbles up to the form and submits it.

![image](https://user-images.githubusercontent.com/7673581/107666840-f2216d00-6c5c-11eb-9443-9f110e1b8ddf.png)

Problem description:

Button clicks should not be bubbling and submitting parent elements.

Suggested solution:

Add a stop propagation or at minimum designate the button as type = button so it doesn't get interpreted as a submit button.

**Comment by inovua-admin** [comment]
Fixed in `4.0.25`
