### ISSUE TITLE
[Bug] Controlled selected prop doesn't work with string or number value

### ISSUE THREAD

**Issue by mijikim** [inovua/reactdatagrid#44]
When a string or number is passed in as `selected`, the grid does not select the appropriate row.  This works if an object with same value is passed in. 

We are using `@inovua/reactdatagrid-enterprise` and it's `v4.0.23`.

**Reproduction**

Below code is a modification of code sample on https://reactdatagrid.io/docs/api-reference#props-selected

```
import React, { useState, useCallback } from 'react'
import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 }

const columns = [
  { name: 'id', defaultWidth: 60, header: 'Id', defaultVisible: false },
  { name: 'name', defaultFlex: 1, header: 'Name' },
  { name: 'country', defaultFlex: 1, header: 'Country',
    render: ({ value }) => flags[value] ? flags[value] : value
  },
  { name: 'age', type: 'number', defaultFlex: 1, header: 'Age' },
  { name: 'email', header: 'Email', defaultFlex: 1 }
]

const App = () => {
  return (
    <div>
      <ReactDataGrid
        idProperty="id"
        multiSelect
        // below will work if passed in { 1: true }
        // also does not work when passed in '1'
        selected={1}
        style={gridStyle}
        columns={columns}
        dataSource={people}
      />
    </div>
  );
}

export default () => <App />
```

**Comment by inovua-admin** [comment]
This is expected behaviour - please read the docs at https://reactdatagrid.io/docs/api-reference#props-selected

If you want multi-select, (you have specified `multiSelect=true` in the example above), you have to pass an object. If you use single selection, you can pass a string or number.

**Comment by inovua-admin** [comment]
In multi-selection, the keys of the object represent the ids of the values being selected.
