### ISSUE TITLE
Filter a complex object

### ISSUE THREAD

**Issue by Ricolo53** [inovua/reactdatagrid#51]
Hello everyone,

- what edition are you using - community
- version for `@inovua/reactdatagrid-community`- 4.0.23

**Relevant code or config**

```
import DataGrid from '@inovua/reactdatagrid-community';
import '@inovua/reactdatagrid-community/index.css';

const dataSource = [
  {basic: 'test1', complex: {name: 'name 1'}},
  {basic: 'test2', complex: {name: 'name 2'}},
  {basic: 'test3', complex: {name: 'name 3'}},
  {basic: 'test4', complex: {name: 'name 4'}},
  {basic: 'test5', complex: {name: 'name 5'}}
],
columns = [
  { name: 'basic', header: 'Basic' },
  { name: 'complex', header: 'Complex', render: ({ data }) => data.complex.name }
],
defaultFilterValue = [
  { name: 'basic', type: 'string', operator: 'contains', value: '' },
  { name: 'complex', type: 'string', operator: 'contains', value: '' }
];

export default function App() {
  return (
    <DataGrid
      columns={columns}
      pagination
      defaultFilterValue={defaultFilterValue}
      dataSource={dataSource} />
  );
}

```

It's look like filter is not possible on complex object.
When I want to filter on complex column, it just return _No records available_

Is someone have an idea how to implement filtering on complex object ?

**Comment by inovua-admin** [comment]
You can define custom filter types or filter operators - read more about it here https://reactdatagrid.io/docs/filtering#filter-types-&-operators and here https://reactdatagrid.io/docs/api-reference#props-filterTypes

**Comment by Ricolo53** [comment]
@inovua-admin I try

```
const filterTypes = Object.assign({}, DataGrid.defaultProps.filterTypes, {
  object: {
    name: 'object',
    operators: [
      {
        name: 'contains',
        fn: ({ value, filterValue, data }) => {
          console.log(value, filterValue, data)

          return true;
        }
      }
    ]
  }
});
```

But problem is _value_ is undefined and I don't know wich column to sort (to implement filtering on data - per exemple data.complex.name). Do I need to implement one custom filter per column..?

**Comment by Ricolo53** [comment]
FYI : I used flat package and transform dataSource like

```
dataSource={this.props.dataSource.map(d => flat(d))}
```
