### ISSUE TITLE
"Select all" checkbox shows selected rows only from the current page

### ISSUE THREAD

**Issue by gandalf516** [inovua/reactdatagrid#52]
community 4.0.22

What you did:
set up grid with checkbox column and pagination, then clicked on "select/deselect all" toggle checkbox

What happened/problem description:
grid shows only items of the current page as selected (onSelectionChange also returns only those items)
Expected: show/return all selected rows upon "select all" + this should be only the filtered ones (from my tests, the "Select all" ignores current filter).

Reproduction repository:
https://codesandbox.io/s/inovua-grid-community-selall-bug-9bjgo
STEPS: either select all, or filter and then select all, and you will always get only the current page rows

Suggested solution:
1. "Select all" should take into account other data pages and the current filter. 
2. grid API should provide a way to get the array of filtered rows.

**Comment by vishal-kadmos** [comment]
@inovua-admin I am also in need of this solution. @inovua-admin would you please update/prioritise this?

**Comment by inovua-admin** [comment]
Fixed in version `5.4.0`. Pass `originalData` instead of `data`.

**Comment by Li-Yeon** [comment]
Hi, how can I select all filtered data only? 
Example: I filtered my data by names, I get 5 data back. I want to select all the 5 data only instead of the whole data (which is original data I think.)
Thank you in advance.
