### ISSUE TITLE
[Date filter] "Today" label is not translated

### ISSUE THREAD

**Issue by marquetd** [inovua/reactdatagrid#53]
Hi, 

i'm using @inovua/reactdatagrid-community` and i cannot find how to translate "Today" message in calendar filter ?

Here "today" is not translatted but days and months are

![image](https://user-images.githubusercontent.com/1841731/108466055-55c22080-7283-11eb-8426-6d879603bebc.png)

I searched in documentation without result :

https://reactdatagrid.io/docs/api-reference#props-i18n

Any help ?

(I try to make this question in stackoverflow but i got this message : 
"Creating the new tag 'reactdatagrid' requires at least 1500 reputation. Try something from the existing tags list instead."

Thanks

**Comment by inovua-admin** [comment]
We've prepared a fix which will go in the next release

**Comment by inovua-admin** [comment]
Should be fixed in `4.0.26` - see https://reactdatagrid.io/docs/api-reference#props-i18n
