### ISSUE TITLE
[bug] selected/onSelectChanged breaks when selected value passed in is `undefined`

### ISSUE THREAD

**Issue by mijikim** [inovua/reactdatagrid#60]
Hello, after I pass in `undefined` as a value of `selected` prop, selecting a row no longer works. `null` works fine.  Considering that the default value for this prop is `undefined` per doc, I would assume that it should also work.

Below is a code snippet using code editor on https://reactdatagrid.io/ and the behavior can be replicated by pressing the button first and then clicking on different rows. 

```
import React, { useState, useCallback } from 'react'
import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 }

const columns = [
  { name: 'id', defaultWidth: 60, header: 'Id', defaultVisible: false },
  { name: 'name', defaultFlex: 1, header: 'Name' },
  { name: 'country', defaultFlex: 1, header: 'Country',
    render: ({ value }) => flags[value] ? flags[value] : value
  },
  { name: 'age', type: 'number', defaultFlex: 1, header: 'Age' },
  { name: 'email', header: 'Email', defaultFlex: 1 }
]

const App = () => {
  const [selected, setSelected] = useState('1');

  const onSelectionChange = useCallback(({ selected }) => {
    console.log('selected', selected);
    setSelected(selected)
  }, [])

  return (
    <div>
      <p>
        Selected rows: {selected == undefined ? 'none' : selected}.
      </p>
      <button onClick={() => { setSelected(undefined) }}>change selection</button>
      <ReactDataGrid
        idProperty="id"
        selected={selected}
        onSelectionChange={onSelectionChange}
        style={gridStyle}
        columns={columns}
        dataSource={people}
      />
    </div>
  );
}

export default () => <App />
```

**Comment by inovua-admin** [comment]
This is as per the docs. `selected=undefined` means selection is disabled, which is also the default behaviour.

**Comment by mijikim** [comment]
I don't think the doc makes it clear that `null` value has to be specifically used when using this as a controlled prop. Neither does it make it clear that if passed in `undefined` value that it will disable the functionality and passing in a valid value won't have an effect afterwards. 

![image](https://user-images.githubusercontent.com/7613891/110135836-369bb680-7d8c-11eb-876a-a8b6418f3edd.png)

This is the type for `selected` prop listed in the doc, which doesn't list `null` as a possible value with `undefined` set to a default value, which can cause confusion when reading it.
