### ISSUE TITLE
missing typescript definitions for filters

### ISSUE THREAD

**Issue by jchn-codes** [inovua/reactdatagrid#63]
Hey there :)

- what edition are you using - community
- version for `@inovua/reactdatagrid-community` - 4.0.30

What you did:

Using the example code https://github.com/inovua/reactdatagrid/blob/master/examples/pages/filters/select-null.page.tsx in a fresh CRA installation: `npx create-react-app reactdatagrid-example --template typescript`. Adding reactdatagrid: `yarn add @inovua/reactdatagrid-community`. Replaced CRA example code with code from your example.

What happened:

I'm evaluating different data grids to use in my company's react typescript applications. When trying to add filters to columns, I encountered missing type definitions. As of your project readme, there should be full Typescript support. 

```bash
TypeScript error in /home/me/dev/reactdatagrid-example/src/components/MyDataGrid.tsx(3,26):
Could not find a declaration file for module '@inovua/reactdatagrid-community/SelectFilter'. '/home/me/dev/reactdatagrid-example/node_modules/@inovua/reactdatagrid-community/SelectFilter/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/inovua__reactdatagrid-community` if it exists or add a new declaration (.d.ts) file containing `declare module '@inovua/reactdatagrid-community/SelectFilter';`  TS7016

    1 | import React from "react";
    2 | import ReactDataGrid from "@inovua/reactdatagrid-community";
  > 3 | import SelectFilter from "@inovua/reactdatagrid-community/SelectFilter";
      |                          ^
    4 | import NumberFilter from "@inovua/reactdatagrid-community/NumberFilter";
    5 | 
    6 | import filterTypes from "@inovua/reactdatagrid-community/filterTypes";
```

This issue is the same for the NumberFilter.

Reproduction repository:

Your example repo: https://github.com/inovua/reactdatagrid/blob/master/examples/pages/filters/select-null.page.tsx

Problem description:

Suggested solution:

Add missing TS definitions to the Filters.

**Comment by inovua-admin** [comment]
Fixed in 4.0.32
