### ISSUE TITLE
Live pagination doesn't work in my case

### ISSUE THREAD

**Issue by ushkvarokilya** [inovua/reactdatagrid#76]
`  
const loadData = ({ skip, sortInfo, limit }) => {
    return trackPromise(
      sessionHttpClient
        .get(
          `${SessionsAPI.BuildGetSessionsToReview(
            126019,
          )}${`?&pageIndex=${skip/limit}`}`,
        )
        .then(({ data }) => {
          return data;
        })
        .catch((err) => {
          throw new Error(err);
        })
    );
  }
      const dataSource = useCallback(loadData, [])  
       return (
<ReactDataGrid
        idProperty="id"
        columns={columns}
        dataSource={dataSource}
        style={{ minHeight: 550 }}
        onSortInfoChange={setSortInfo}
        defaultSortInfo={defaultSortInfo}
        defaultFilterValue={filterValue}
        onFilterValueChange={setFilterValue}
        limit="20"
        livePagination
        pagination
      />);`
      
      in this case,reaching the end of data limit doesn't trigger the live reload. -limit and skip aren't changed

**Comment by inovua-admin** [comment]
Please make sure you fully describe the issue, include any relevant information (which edition you're using, which version etc.) and also create a minimal code example which can be run standalone - either github repo or codesandbox. Issues without a minimal reproduction code will be closed
