### ISSUE TITLE
Multi-Select with wrap=true, wraps the selections over the column cell value

### ISSUE THREAD

**Issue by KatyMan** [inovua/reactdatagrid#78]
I am using the community version (4.1.2) on Chrome

I have defined a column as having a select filter with multiple: true and wrapMultiple: true (as follows)
    {
      name: 'type',
      header: 'Type',
      flex: 1,
      minWidth: 150,
      filterEditor: SelectFilter,
      filterEditorProps: {
        multiple: true,
        wrapMultiple: true,
        dataSource: typeSelectMapping
      },
      render: ({ value }) => formatType(value),
      sort: (type1, type2) => {
        return formatType(type1).localeCompare(formatType(type2));
      }
    },

The Select drop-down displays correctly and will allow me select multiple values to filter on.  However, when the selected values are displayed and wrapped into the grid, I was expecting them to remain in the 'filter row"--expanding it as required to contain the selected values.  That is not the behavior I am seeing.  Instead, the 'wrapped' values are displayed over the data values making them impossible to see.  Is this the intended behavior.  If so, I would consider this a bugs as after selecting several items to filter on, the data row is impossible to see. If not, is there any way to work around this existing behavior.

Here is a screenshot of what I am seeing.
<img width="474" alt="Screen Shot 2021-04-05 at 1 53 32 PM" src="https://user-images.githubusercontent.com/5825617/113613833-5f2b0080-9617-11eb-8138-b3e75808e47e.png">

**Comment by KatyMan** [comment]
Sort of related to this issue... Is there a way to enable filtering, but allow the filterEditors to be displayed somewhere other than directly below each column header (like a filtering side-bar)

**Comment by inovua-admin** [comment]
1. Even the wrapMultiple prop is fully supported in the editor itself, we currently don't support it in the ReactDataGrid. It's on our radar anyway;
2. This functionality in on our roadmap for the Enterprise Edition.

**Comment by riguy14** [comment]
Workaround for anyone getting this issue still is to set the `maxHeight` as `none` on the item below. Both themes are covered here, but feel free to only add the one you need.
```
.InovuaReactDataGrid--theme-default-light .InovuaReactDataGrid__column-header__filter-wrapper .InovuaReactDataGrid__column-header__filter, .InovuaReactDataGrid--theme-default-dark .InovuaReactDataGrid__column-header__filter-wrapper .InovuaReactDataGrid__column-header__filter {
    max-height: none;
}
```
