### ISSUE TITLE
cancelEdit is undefined

### ISSUE THREAD

**Issue by carlos-fs** [inovua/reactdatagrid#81]
- what edition are you using - **community**
- version for `@inovua/reactdatagrid-community` - **4.0.32**

Relevant code or config (took from [Inline Edit](https://reactdatagrid.io/docs/inline-edit)):

```typescript
import React, { useState, useCallback } from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 };

const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, minWidth: 300, type: 'number' },
  { name: 'name', header: 'Name', defaultFlex: 1, minWidth: 250 },
  { name: 'country', header: 'Country', defaultFlex: 1, minWidth: 100, render: ({ value })=> flags[value] ? flags[value]: value },
  { name: 'city', header: 'City', defaultFlex: 1, minWidth: 300 },
  { name: 'age', header: 'Age', minWidth: 150, type: 'number' }
];

const App = () => {
  const [grid, setGrid] = useState(null);
  const [dataSource, setDataSource] = useState(people);
  
  const onEditStart = (data) => {
    console.log(data);
    if (!grid || !grid.current) {
      return;
    }
    
    console.log('cancelling edit');
    console.log(grid.current.cancelEdit);
    console.log('editing cancelled');
  }

  const onEditComplete = useCallback(({ value, columnId, rowIndex }) => {
    const data = [...dataSource];
    data[rowIndex][columnId] = value;

    setDataSource(data);
  }, [dataSource])

  return (
    <div>
      <h3>Grid with inline edit</h3>
      <ReactDataGrid
        onReady={setGrid}
        idProperty="id"
        style={gridStyle}
        onEditStart={onEditStart}
        onEditComplete={onEditComplete}
        editable={true}
        columns={columns}
        dataSource={dataSource}
      />
    </div>
  );
}

export default () => <App />
```

What you did:
I need to cancel the row edition from a button. 
The documentation outlines there's a `cancelEdit` function that can be called, it doesn't say where it is, but I assumed it's located on the grid ref that can be obtained using the `onReady` callback.

What happened:
Just for demonstration purposes, I'm checking if `gridRef.current.cancelEdit` is defined whenever a new edit starts.
Right now is returning `undefined`

Reproduction repository:
[You can reproduce it on your docs](https://reactdatagrid.io/docs/inline-edit)

![image](https://user-images.githubusercontent.com/77641694/114214687-7c164b00-9919-11eb-98dc-910ed7d3179c.png)

Problem description:
The `grid` ref object does not have a `cancelEdit` function defined.

Suggested solution:
Haven't had the chance to review the repo in order to trace the issue.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.10`
