### ISSUE TITLE
Warning about invalid property type for the computedEditable property

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#84]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - latest

What you did:
Using a function for the column.editable property

What happened:

![image](https://user-images.githubusercontent.com/11202960/114592950-bf89f580-9c48-11eb-8f88-e2199646e850.png)

Problem description:

Using a function that returns a boolean value for a column.editable property causes the warning in the console window

**Comment by inovua-admin** [comment]
Fixed in `v4.1.6`
