### ISSUE TITLE
Combobox label disappears when props.value updated and multiple==true

### ISSUE THREAD

**Issue by tarikkarsi** [inovua/reactdatagrid#85]
What you did:
Created an multiselect combobox and changed props.value after initialization.

What happened:
Tag label strings are lost and id's are shown as labels.
First value
<img width="307" alt="Screen Shot 2021-04-14 at 10 38 01" src="https://user-images.githubusercontent.com/3969020/114672211-8f585a80-9d0d-11eb-8a35-1ffcfc0ca50a.png">
After changing props value
<img width="307" alt="Screen Shot 2021-04-14 at 10 35 55" src="https://user-images.githubusercontent.com/3969020/114672003-59b37180-9d0d-11eb-8fb4-42ff5c21e5af.png">

Reproduction repository:
https://codesandbox.io/s/reactdatagrid-combobox-e9imb

Problem description:
Changing combobox props value after initialization brokes label texts. Trying to update combobox value after gathering data from backend service.

Suggested solution:
In Combobox.js file:
getSelectedItems function only searches labels inside valueMap. Since valuemap does not contain the updated value, the label information disappears.
getItemLabel should be used for getting labels not to make code duplication

```javascript
function getSelectedItems() {
      var _this8 = this;

      var valueMap = this.getValueMap();
      var value = this.getValue();
      var items = null;

      if (value) {
        value = Array.isArray(value) ? value : [value];
        items = value.map((id) => {
          return valueMap[id] || {
            id: (0, _typeof2.default)(id) === 'object' ? _this8.getIdProperty(id) : id,
            label: (0, _typeof2.default)(id) === 'object' ? _this8.getDisplayProperty(id) : this.getItemLabel(id)
          };
        });
      }

      return items;
    }
```

This requires removing return statement in getItemLabel function when multiselect enabled.

```javascript
function getItemLabel(id) {
      id = id === undefined ? this.getValue() : id;
      var valueMap = this.getValueMap();
      var dataMap = this.getDataMap();
      var label;

      if (valueMap && valueMap[id]) {
        label = valueMap[id].label;
      } else if (dataMap && dataMap[id]) {
        label = this.getDisplayProperty(dataMap[id]);
      }

      if (label === undefined) {
        label = this.props.defaultDisplayValue !== undefined && id != null ? this.props.defaultDisplayValue : id;
      }

      return label;
    }
```

I tested with datagrid column filter with multiselect and combobox independent from datagrid and did not see any regression.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.6`
