### ISSUE TITLE
Row selection is not always applied

### ISSUE THREAD

**Issue by lavoiekeven** [inovua/reactdatagrid#9]
- what edition are you using - community (But the problem seems to happen on both version)
- version for both

Relevant code or config

What you did:
Just click on a list with the option enableSelection enabled

What happened:
The border is always applied on the last clicked row but the row background is not always applied

Reproduction repository:
You can easily reproduce the problem with example provided on the page https://reactdatagrid.io/docs/row-selection.
The probleme is also happening in the community version.

![ezgif com-gif-maker](https://s8.gifyu.com/images/ezgif.com-gif-makerd87f56f976a2817d.gif)

Problem description:
onSelectionChange callback is not always called. This causes that the last clicked cell is not always selected.

Suggested solution:
The selected row style must be applied.

**Comment by inovua-admin** [comment]
Row selection and active row are two different concepts - the border around a row indicates it's the active row (active row refers to navigation), while the background indicates it's selected. When you click a row, it becomes both active and selected, but you can then navigate with with arrow keys to different rows.

After a few tries, we have managed to reproduce the issue - clicking a row sometimes only makes it active, but not selected. Thanks for the bug report!

We're working on a fix!

**Comment by chhuang** [comment]
Is it possible to change the style/color of the active border?

**Comment by AndreeaStirbu** [comment]
Is it possible to completly remove the active borders?

**Comment by inovua-admin** [comment]
If you want the active row to be selected too, set `preventRowSelectionOnClickWithMouseMove` to `false`.
The active row indicator can be displayed or be hidden via `showActiveRowIndicator` prop. See docs [here](https://reactdatagrid.io/docs/api-reference#props-showActiveRowIndicator), and also you can styling it via `activeRowIndicatorClassName` prop. See docs [here](https://reactdatagrid.io/docs/api-reference#props-activeRowIndicatorClassName).
