### ISSUE TITLE
Row reorder column is hidden when columnOrder or defaultColumnOrder properties are used

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#91]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - latest

Relevant code or config

```javascript
import React from 'react'
import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 550 }

const columns = [
  { name: 'id', header: 'Id', defaultWidth: 60 },
  { name: 'name', header: 'Name', defaultWidth: 120 },
  { name: 'country', header: 'Country', defaultWidth: 120,
    render: ({ value }) => flags[value] ? flags[value] : value
  },
  { name: 'age', header: 'Age', type: 'number', defaultWidth: 120 }
]

const App = () => {
  return (
    <div>
      <h3>Drag to reorder</h3>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        rowHeight={40}
        rowReorderColumn
        columns={columns}
        dataSource={[].concat(people)}
        defaultColumnOrder={['id', 'name', 'country', 'age']}
      />
    </div>
  )
}

export default () => <App />
```

What you did:
Set rowReorderColumn and  defaultColumnOrder (or columnOrder)

What happened:
row reorder column is hidden

![image](https://user-images.githubusercontent.com/11202960/115059913-71712e00-9ea4-11eb-84d0-a7ba2789cd9b.png)

Problem description:

Seems that the reason it is hidden is that here:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/normalizeColumns/useColumnInfo.ts#L235

neither onRowReorder nor rowReorderColumn are passed. Also, even if rowReorderColumn can be used without onRowReorder here:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/normalizeColumns/index.ts#L286

and here:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/normalizeColumns/index.ts#L352

only onRowReorder is checked, not rowReorderColumn.

This will probably have another implication that the row reorder column will never be locked even though the intent is there in the code: (https://github.com/inovua/reactdatagrid/blob/master/community-edition/normalizeColumns/index.ts#L286)

Suggested solution:

Fix the issues above by passing missing parameters and adding handling of a missing parameter.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.7`
