### ISSUE TITLE
Row reorder 'drop-allowed' indicator should not be shown when the row is being dropped just after itself

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#92]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-community`or `@inovua/reactdatagrid-enterprise` - latest

Relevant code or config

```javascript
```

What you did:

As you see on the screenshot below dragging a row over its lower bounds shows that insertion is valid even though the drop would not result in any change.

![image](https://user-images.githubusercontent.com/11202960/115076840-5d382b80-9eba-11eb-8f8c-b421b1515ff7.png)

Suggested solution:

Here:

https://github.com/inovua/reactdatagrid/blob/master/enterprise-edition/EnterpriseColumnLayout.tsx#L460

the code should instead do this:

```
if (dropIndex === dragIndex || dropIndex === dragIndex + 1) {
      return;
}
```

**Comment by inovua-admin** [comment]
Fixed in `v4.1.7`
