### ISSUE TITLE
When custom cell editor is used calling editorProps.onCancel prevents a call to editorProps.onComplete to work properly

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#97]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - latest

Relevant code or config
This bug is hard to reproduce using the standard examples because it involves using a custom cell editor but I will describe it in details below and it should be enough to see the issue.

What you did:
We use custom cell editors in our grid that respond to a user hitting Escape key (we call editorProps.onCancel in that case) or Enter key (we call editorProps.onComplete in that case). The issue is that if user once cancelled editing for a cell by hitting Escape key and then later tried to edit the same cell and this time tried to save it by hitting Enter key the save would not work because internally the cell component maintains a isCancelled property that it sets to true when editorProps.onCancel is called:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/Layout/ColumnLayout/Cell/index.tsx#L998

Later when user double clicks the same cell and this time tries to change a value (editorProps.onChange) and hit Enter calling editorProps.onComplete does not work because of this code:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/Layout/ColumnLayout/Cell/index.tsx#L1022

Suggested solution:

The fix should be easy enough. when cell gets into an edit mode startEdit method is called:

https://github.com/inovua/reactdatagrid/blob/master/community-edition/Layout/ColumnLayout/Cell/index.tsx#L957

Here the this.isCancelled property should be reset to false.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.8`
