### ISSUE TITLE
React warning in the console panel about a ref property being accessed

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#98]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - latest

What happened:

When double-clicking a cell to edit this warning appears in the browser console:

![image](https://user-images.githubusercontent.com/11202960/115304499-46940d80-a122-11eb-8d18-037b483b905f.png)

Here's the call stack:

![image](https://user-images.githubusercontent.com/11202960/115305044-f6697b00-a122-11eb-9252-652eb3d45ccd.png)

It looks like React does not like that one of the accessed properties in the 'equal' method is a ref.

**Comment by inovua-admin** [comment]
Fixed in `v4.1.8`
