### ISSUE TITLE
Active row index is not updated when Enter or Tab key cell navigation is used

### ISSUE THREAD

**Issue by yurigenin** [inovua/reactdatagrid#99]
- what edition are you using - enterprise
- version for `@inovua/reactdatagrid-enterprise` - latest

Relevant code or config

```javascript
import React, { useState, useCallback } from 'react'

import ReactDataGrid from '@inovua/reactdatagrid-enterprise'
import '@inovua/reactdatagrid-enterprise/index.css'

import people from './people'
import flags from './flags'

const gridStyle = { minHeight: 350 };

const isStartEditKeyPressed = ({ event }) => event.key === 'k' && event.ctrlKey;

const columns = [
  { name: 'id', header: 'Id', defaultVisible: false, minWidth: 50, type: 'number', editable: false, },
  { name: 'name', header: 'Name', defaultFlex: 1, minWidth: 200 },
  { name: 'country', header: 'Country', defaultFlex: 1, minWidth: 200, render: ({ value })=> flags[value]? flags[value] : value },
  { name: 'city', header: 'City', defaultFlex: 1, minWidth: 200 },
  { name: 'age', header: 'Age', minWidth: 50, type: 'number', editable: false }
];

const App = () => {
  const [dataSource, setDataSource] = useState(people);

  const onEditComplete = useCallback(({ value, columnId, rowIndex }) => {
    const data = [...dataSource];
    data[rowIndex][columnId] = value;

    setDataSource(data);
  }, [dataSource])

  return (
    <div>
      <h4>AGE columns is not editable. Use TAB/SHIFT+TAB while editing to navigate to next/prev editable cell.</h4>
      <ReactDataGrid
        idProperty="id"
        style={gridStyle}
        onEditComplete={onEditComplete}
        editable={true}
        columns={columns}
        dataSource={dataSource}
      />
    </div>
  );
}

export default () => <App />
```

What happened:

This results on a condition like that:

![image](https://user-images.githubusercontent.com/11202960/115314053-b2ca3d80-a131-11eb-87d2-a970b57847f2.png)

As you see, the active row index and the edited cell row index are not the same. As cell editor changes the active row index should follow it. Excel does exactly that.

When user double clicks any cell for editing it automatically makes the row active. The same should happen when the editor is invoked programmatically.

Another related issue is that the active row indicator becomes invisible when you double click a cell to edit. But when you use Enter or Tab navigation it reappears as soon as the editor is invoked for a different row.

1. Initial condition:

![image](https://user-images.githubusercontent.com/11202960/115314755-12751880-a133-11eb-9e51-e94eaf203da1.png)

2. After double-click on the 'Bobby' cell (active row indicator is gone):

![image](https://user-images.githubusercontent.com/11202960/115314821-36d0f500-a133-11eb-978f-511041f48477.png)

3. After hitting Enter key twice (active row indicator reappears):

![image](https://user-images.githubusercontent.com/11202960/115314881-52d49680-a133-11eb-8f7d-964ee15b35ef.png)

**Comment by inovua-admin** [comment]
Fixed in `v4.1.8`
